Repository ianstormtaylor/slate, pull requests merged in 2018-04, with the labels that each got.

#1745 Feature: setTextByKey and replaceTextByKey
  packages/slate/src/changes/by-key.js
  packages/slate/test/changes/by-key/replace-text-by-key/replace-with-active-marks-with-data.js
  packages/slate/test/changes/by-key/replace-text-by-key/replace-with-active-marks.js
  packages/slate/test/changes/by-key/replace-text-by-key/replace-with-mark-and-active-mark.js
  packages/slate/test/changes/by-key/replace-text-by-key/replace-with-node-index-mark.js
  packages/slate/test/changes/by-key/replace-text-by-key/replace-without-any-marks.js
  packages/slate/test/changes/by-key/set-text-by-key/replace-with-string-and-mark.js
  packages/slate/test/changes/by-key/set-text-by-key/replace-with-string.js
  packages/slate/test/helpers/h.js
Labels: feature

#1760 Extract hotkey and environment detection into separate packages
  packages/slate-dev-environment/Changelog.md
  packages/slate-dev-environment/Readme.md
  packages/slate-dev-environment/package.json
  packages/slate-dev-environment/src/index.js
  packages/slate-dev-environment/test/index.js
  packages/slate-hotkeys/Changelog.md
  packages/slate-hotkeys/Readme.md
  packages/slate-hotkeys/package.json
  packages/slate-hotkeys/src/index.js
  packages/slate-hotkeys/test/index.js
  packages/slate-react/package.json
  packages/slate-react/src/components/content.js
  packages/slate-react/src/constants/hotkeys.js
  packages/slate-react/src/plugins/after.js
  packages/slate-react/src/plugins/before.js
  packages/slate-react/src/utils/clone-fragment.js
  packages/slate-react/src/utils/find-range.js
  packages/slate-react/src/utils/scroll-to-selection.js
  support/rollup/config.js
Labels: feature

#1783 refactor: remove useless .indexOf to improve perf
  packages/slate/src/models/node.js
Labels: improvement, ⚑ performance

#1796 Remove unused dependencies
  package.json
  yarn.lock
Labels: debt

#1734 fix: make void node selectable for edge case, close: #1639
  packages/slate-react/src/components/void.js
  packages/slate-react/test/rendering/fixtures/custom-block-void.js
  packages/slate-react/test/rendering/fixtures/custom-inline-void.js
Labels: bug

#1711 IME - remove extra force re-renders on onCompositionStart/End
  packages/slate-react/src/components/content.js
  packages/slate-react/src/plugins/before.js
Labels: bug

#1751 Update adding-event-handlers.md
  docs/walkthroughs/adding-event-handlers.md
Labels: docs

#1742 Fix hanging selection paste in insertFragmentAtRange
  packages/slate/src/changes/at-range.js
  packages/slate/test/changes/at-current-range/insert-fragment/hanging-selection-single-block.js
Labels: bug

#1753 Fix spell check bug
  docs/guides/rendering.md
  docs/walkthroughs/saving-and-loading-html-content.md
  docs/walkthroughs/using-plugins.md
  examples/code-highlighting/index.js
  examples/hovering-menu/index.js
  examples/huge-document/index.js
  examples/markdown-preview/index.js
  examples/paste-html/index.js
  examples/rich-text/index.js
  examples/search-highlighting/index.js
  examples/syncing-operations/index.js
  examples/tables/index.js
  packages/slate-react/src/components/leaf.js
  packages/slate-react/src/plugins/after.js
  packages/slate-react/test/rendering/fixtures/custom-decorator.js
  packages/slate-react/test/rendering/fixtures/custom-mark.js
Labels: bug

#1747 Fix splitBlock bug with hanging selection
  packages/slate/src/changes/at-current-range.js
  packages/slate/src/changes/at-range.js
  packages/slate/test/changes/at-current-range/split-block/with-delete-hanging-selection.js
  packages/slate/test/changes/at-current-range/split-block/with-marks.js
Labels: bug

#1779 Ensure cursor is shown after delete hanging selection
  packages/slate/src/changes/at-current-range.js
  packages/slate/test/changes/at-current-range/delete-forward/start-text-middle-inline.js
Labels: bug

#1781 Update debug package in package.json
  packages/slate-react/package.json
  packages/slate/package.json
  yarn.lock
Labels: improvement

#1777 slate-hyperscript tests and decorations
  packages/slate-hyperscript/Changelog.md
  packages/slate-hyperscript/src/index.js
  packages/slate-hyperscript/test/custom/custom-tags.js
  packages/slate-hyperscript/test/decorations/across-blocks.js
  packages/slate-hyperscript/test/decorations/across-marks.js
  packages/slate-hyperscript/test/decorations/deep-anchors.js
  packages/slate-hyperscript/test/decorations/intersecting-marks.js
  packages/slate-hyperscript/test/decorations/multiple.js
  packages/slate-hyperscript/test/decorations/nested.js
  packages/slate-hyperscript/test/decorations/overlapping.js
  packages/slate-hyperscript/test/decorations/single.js
  packages/slate-hyperscript/test/default/single-block.js
  packages/slate-hyperscript/test/default/with-marks-and-inlines.js
  packages/slate-hyperscript/test/index.js
  packages/slate-hyperscript/test/normalize/on-by-default.js
  packages/slate-hyperscript/test/normalize/optionally-disabled.js
  packages/slate-hyperscript/test/selections/cursor-in-block.js
  packages/slate-hyperscript/test/selections/cursor-in-mark.js
  packages/slate-hyperscript/test/selections/range-across-blocks.js
  packages/slate-hyperscript/test/selections/range-in-block.js
  packages/slate-hyperscript/test/selections/selection-tag-with-matching-key.js
Labels: debt, improvement

#1366 Limit melding behavior in `insertFragmentAtRange`
  packages/slate/src/changes/at-range.js
Labels: improvement

#1670 Update change.md to include setValue
  docs/reference/slate/change.md
Labels: docs
