Repository ianstormtaylor/slate, pull requests merged in 2018-10, with the labels that each got.

#2222 Fix normalizing dirty paths
  packages/slate-hyperscript/test/fixtures/cursor-across-blocks-and-inlines.js
  packages/slate/src/models/change.js
  packages/slate/src/utils/path-utils.js
Labels: bug

#2226 fix activeMarks for intersecting marks text
  packages/slate/src/models/text.js
  packages/slate/test/models/text/marks/get-active-marks/intersecting-marks-text.js
Labels: bug

#2227 serialize path as well in Operation.toJSON
  packages/slate/src/models/operation.js
Labels: bug

#2240 Fix delete undo
  packages/slate/src/changes/on-selection.js
  packages/slate/src/models/change.js
  packages/slate/test/history/undo/remove-text.js
Labels: bug

#2234 Replace "zero width whitspace" with "zero width no break" character
  packages/slate-react/src/components/leaf.js
  packages/slate-react/test/rendering/fixtures/custom-block-blurred.js
  packages/slate-react/test/rendering/fixtures/custom-block-focused.js
  packages/slate-react/test/rendering/fixtures/custom-block-selected.js
  packages/slate-react/test/rendering/fixtures/custom-block-void.js
  packages/slate-react/test/rendering/fixtures/custom-inline-multiple.js
  packages/slate-react/test/rendering/fixtures/custom-inline-void.js
  packages/slate-react/test/rendering/fixtures/custom-inline.js
  packages/slate-react/test/rendering/fixtures/default-block-with-inline.js
  packages/slate-react/test/rendering/fixtures/empty-block.js
  packages/slate-react/test/rendering/fixtures/readonly-custom-inline-void.js
Labels: bug

#2247 Take Blocks as word break to fix word counting in example
  examples/plugins/word-count.js
Labels: examples

#2265 Update ‘Submitting Pull Requests’ to refer to an active label
  Contributing.md
Labels: docs

#2256 Fix insertTextAtRange selection
  packages/slate/src/commands/at-range.js
  packages/slate/test/changes/at-range/insert-text-at-range/non-matching-section-and-range.js
Labels: bug

#2266 Add possibility to specify a custom delimiter to slate-plain-serializer
  packages/slate-plain-serializer/src/index.js
  packages/slate-plain-serializer/test/deserialize/custom-delimiter.js
  packages/slate-plain-serializer/test/serialize/custom-delimiter.js
Labels: feature

#2277 Fix bolded text in input-tester initial value
  examples/input-tester/value.json
Labels: examples

#2283 add favicon to the examples
  examples/favicon.ico
Labels: examples

#2294 Fixed KeyDown handler signature in code snippet
  docs/guides/commands-and-queries.md
Labels: docs

#2169 fix: use text utils to move forward and backward by word
  packages/slate-hotkeys/src/index.js
  packages/slate-react/src/plugins/after.js
  packages/slate/src/commands/on-selection.js
  packages/slate/test/commands/on-selection/move-anchor-backward/default.js
  packages/slate/test/commands/on-selection/move-anchor-backward/from-collapsed.js
  packages/slate/test/commands/on-selection/move-anchor-backward/out-of-reverse.js
  packages/slate/test/commands/on-selection/move-anchor-backward/param.js
  packages/slate/test/commands/on-selection/move-anchor-forward/default.js
  packages/slate/test/commands/on-selection/move-anchor-forward/from-collapsed.js
  packages/slate/test/commands/on-selection/move-anchor-forward/into-reverse.js
  packages/slate/test/commands/on-selection/move-anchor-forward/param.js
  packages/slate/test/commands/on-selection/move-backward/default.js
  packages/slate/test/commands/on-selection/move-backward/expanded.js
  packages/slate/test/commands/on-selection/move-backward/param.js
  packages/slate/test/commands/on-selection/move-backward/reversed.js
  packages/slate/test/commands/on-selection/move-end-backward/default.js
  packages/slate/test/commands/on-selection/move-end-backward/from-collapsed.js
  packages/slate/test/commands/on-selection/move-end-backward/into-reverse.js
  packages/slate/test/commands/on-selection/move-end-backward/out-of-reverse.js
  packages/slate/test/commands/on-selection/move-end-backward/param.js
  packages/slate/test/commands/on-selection/move-end-backward/reversed.js
  packages/slate/test/commands/on-selection/move-end-forward/default.js
  packages/slate/test/commands/on-selection/move-end-forward/from-collapsed.js
  packages/slate/test/commands/on-selection/move-end-forward/param.js
  packages/slate/test/commands/on-selection/move-end-forward/reversed.js
  packages/slate/test/commands/on-selection/move-focus-backward/default.js
  packages/slate/test/commands/on-selection/move-focus-backward/from-collapsed.js
  packages/slate/test/commands/on-selection/move-focus-backward/into-reverse.js
  packages/slate/test/commands/on-selection/move-focus-backward/param.js
  packages/slate/test/commands/on-selection/move-focus-forward/default.js
  packages/slate/test/commands/on-selection/move-focus-forward/from-collapsed.js
  packages/slate/test/commands/on-selection/move-focus-forward/out-of-reverse.js
  packages/slate/test/commands/on-selection/move-focus-forward/param.js
  packages/slate/test/commands/on-selection/move-forward/default.js
  packages/slate/test/commands/on-selection/move-forward/expanded.js
  packages/slate/test/commands/on-selection/move-forward/param.js
  packages/slate/test/commands/on-selection/move-forward/reversed.js
  packages/slate/test/commands/on-selection/move-start-backward/default.js
  packages/slate/test/commands/on-selection/move-start-backward/from-collapsed.js
  packages/slate/test/commands/on-selection/move-start-backward/param.js
  packages/slate/test/commands/on-selection/move-start-backward/reversed.js
  packages/slate/test/commands/on-selection/move-start-forward/default.js
  packages/slate/test/commands/on-selection/move-start-forward/from-collapsed.js
  packages/slate/test/commands/on-selection/move-start-forward/into-reverse.js
  packages/slate/test/commands/on-selection/move-start-forward/out-of-reverse.js
  packages/slate/test/commands/on-selection/move-start-forward/param.js
  packages/slate/test/commands/on-selection/move-start-forward/reversed.js
  packages/slate/test/commands/on-selection/move-word-backward/collapsed.js
  packages/slate/test/commands/on-selection/move-word-backward/expanded.js
  packages/slate/test/commands/on-selection/move-word-backward/reversed.js
  packages/slate/test/commands/on-selection/move-word-forward/collapsed.js
  packages/slate/test/commands/on-selection/move-word-forward/expanded.js
  packages/slate/test/commands/on-selection/move-word-forward/reversed.js
Labels: bug

#2310 Update change.md
  docs/reference/slate/change.md
Labels: docs

#2298 Fix cloneFragment conditional handling of clipboardData.setData
  packages/slate-react/src/utils/clone-fragment.js
Labels: bug

#2314 fix: extend forward / backward
  package.json
  packages/slate-hotkeys/package.json
  yarn.lock
Labels: bug

#2316 fix: use ancestors for dirt paths
  packages/slate/src/controllers/change.js
  packages/slate/src/utils/path-utils.js
Labels: bug

#2300 Use <br /> inside empty block so those appear selected
  packages/slate-react/src/components/leaf.js
  packages/slate-react/test/rendering/fixtures/custom-block-blurred.js
  packages/slate-react/test/rendering/fixtures/custom-block-focused.js
  packages/slate-react/test/rendering/fixtures/custom-block-selected.js
  packages/slate-react/test/rendering/fixtures/custom-inline-void.js
  packages/slate-react/test/rendering/fixtures/empty-block.js
  packages/slate-react/test/rendering/fixtures/readonly-custom-inline-void.js
Labels: improvement

#2218 Prevent crash when handling composition when selection is not collapsed
  packages/slate-react/src/plugins/before.js
Labels: bug

#2271 Alter cursor placement in `insertFragment` tests to reflect reality
  packages/slate/test/commands/at-current-range/insert-fragment/end-inline.js
  packages/slate/test/commands/at-current-range/insert-fragment/middle-inline-fragment-inline.js
  packages/slate/test/commands/at-current-range/insert-fragment/start-inline.js
Labels: debt

#2324 Fix invalid transform path in move_node operation
  packages/slate/src/utils/path-utils.js
  packages/slate/test/commands/at-current-range/delete/non-void-triple.js
  packages/slate/test/commands/at-current-range/delete/void-inline-as-last-with-non-void-previous-siblings.js
Labels: bug

#2327 When trying to move a node from a path to an equal path, ignore it
  packages/slate/src/commands/by-path.js
  packages/slate/src/controllers/change.js
  packages/slate/src/operations/apply.js
  packages/slate/src/operations/invert.js
  packages/slate/test/commands/by-path/move-node-by-path/path-equals-new-path.js
  packages/slate/test/operations/apply/move-node/path-equals-new-path.js
Labels: improvement

#2343 Fix deprecated editor.change in after/onCut
  packages/slate-react/src/plugins/after.js
Labels: bug

#2357 Checks for nodes in isLeafBlock & isLeafInline
  packages/slate/src/interfaces/element.js
Labels: bug
