Repository ianstormtaylor/slate, pull requests merged in 2018-11, with the labels that each got.

#2363 fix: update mentions example to slate 0.43
  examples/mentions/index.js
Labels: examples

#2362 Fix a typo in the docs
  docs/guides/commands-and-queries.md
Labels: docs

#2367 Fix delete intent
  packages/slate/src/commands/at-range.js
  packages/slate/src/commands/with-intent.js
  packages/slate/src/plugins/core.js
  packages/slate/test/commands/at-current-range/delete/across-blocks-inlines.js
  packages/slate/test/commands/at-current-range/split-block/with-delete-across-blocks-and-inlines.js
  packages/slate/test/commands/at-current-range/split-block/with-delete-hanging-selection.js
Labels: bug, improvement

#2370 Remove `renderPlaceholder`
  docs/guides/rendering.md
  docs/reference/slate-react/editor.md
  docs/reference/slate-react/plugins.md
  packages/slate-react-placeholder/Changelog.md
  packages/slate-react-placeholder/Readme.md
  packages/slate-react-placeholder/package.json
  packages/slate-react-placeholder/src/index.js
  packages/slate-react-placeholder/test/index.js
  packages/slate-react/Changelog.md
  packages/slate-react/package.json
  packages/slate-react/src/components/editor.js
  packages/slate-react/src/components/leaf.js
  packages/slate-react/src/components/node.js
  packages/slate-react/src/plugins/after.js
  packages/slate-react/src/plugins/before.js
  packages/slate-react/src/plugins/dom.js
  packages/slate-react/src/plugins/react.js
  packages/slate-react/src/utils/find-dom-point.js
  packages/slate-react/test/rendering/fixtures/custom-block-blurred.js
  packages/slate-react/test/rendering/fixtures/custom-block-focused.js
  packages/slate-react/test/rendering/fixtures/custom-block-multiple.js
  packages/slate-react/test/rendering/fixtures/custom-block-selected.js
  packages/slate-react/test/rendering/fixtures/custom-block-void.js
  packages/slate-react/test/rendering/fixtures/custom-block.js
  packages/slate-react/test/rendering/fixtures/custom-decorator.js
  packages/slate-react/test/rendering/fixtures/custom-inline-multiple.js
  packages/slate-react/test/rendering/fixtures/custom-inline-void.js
  packages/slate-react/test/rendering/fixtures/custom-inline.js
  packages/slate-react/test/rendering/fixtures/custom-mark.js
  packages/slate-react/test/rendering/fixtures/default-block-with-inline.js
  packages/slate-react/test/rendering/fixtures/default-block.js
  packages/slate-react/test/rendering/fixtures/empty-block.js
  packages/slate-react/test/rendering/fixtures/nested-text-direction.js
  packages/slate-react/test/rendering/fixtures/readonly-custom-inline-void.js
  packages/slate-react/test/rendering/fixtures/text-direction.js
  packages/slate/src/interfaces/element.js
  packages/slate/src/models/text.js
  support/rollup/config.js
Labels: improvement, ✶ breaking

#2374 Check if inline ancestor exists before using it in wrapInlineAtRange
  packages/slate/src/commands/at-range.js
  packages/slate/test/commands/at-current-range/wrap-inline/collapsed-range-without-parent-void-inline.js
Labels: bug

#2373 Data property for Operation model
  examples/syncing-operations/index.js
  packages/slate/src/models/operation.js
  packages/slate/test/index.js
  packages/slate/test/models/operation/create/add-mark-with-data.js
  packages/slate/test/models/operation/create/add-mark-without-data.js
Labels: feature

#2379 Fix broken "Versions" example
  examples/versions/index.js
Labels: examples

#2380 fix: support mobile devices in examples
  support/webpack/config.js
Labels: examples

#2387 added the schema reference to the list of documents for gitbook
  book.json
  docs/Summary.md
Labels: docs

#2396 fix focusing across multiple editors
  packages/slate-react/src/components/content.js
  packages/slate-react/src/constants/event-handlers.js
  packages/slate-react/src/plugins/after.js
Labels: bug

#2399 Add `node.getLeafXAtRange` and `node.getRootXAtRange`
  benchmark/slate/models/get-leaf-blocks-at-range.js
  benchmark/slate/models/get-leaf-inlines-at-range.js
  docs/reference/slate/node.md
  packages/slate/src/commands/at-range.js
  packages/slate/src/interfaces/element.js
  packages/slate/src/models/value.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/multiple-blocks.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/nested-blocks-cursor-in-first-leaf-of-first-parent.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/nested-blocks-cursor-in-first-leaf-of-second-parent.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/nested-blocks-cursor-in-second-leaf-of-first-parent.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/nested-blocks-selection-overlapping-multiple-blocks.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/nested-blocks-selection-overlapping-texts-in-second-parent.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/nested-blocks-selection-spanning-first-text.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/single-block-with-inline.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/single-block.js
  packages/slate/test/models/node/get-leaf-blocks-at-range-as-array/single-void-block.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/multiple-blocks.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/nested-blocks-cursor-in-first-leaf-of-first-parent.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/nested-blocks-cursor-in-first-leaf-of-second-parent.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/nested-blocks-cursor-in-second-leaf-of-first-parent.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/nested-blocks-selection-overlapping-multiple-blocks.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/nested-blocks-selection-overlapping-texts-in-second-parent.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/nested-blocks-selection-spanning-first-text.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/single-block-with-inline.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/single-block.js
  packages/slate/test/models/node/get-leaf-blocks-at-range/single-void-block.js
  packages/slate/test/models/node/get-leaf-inlines-at-range-as-array/multiple-blocks-no-inline.js
  packages/slate/test/models/node/get-leaf-inlines-at-range-as-array/multiple-blocks.js
  packages/slate/test/models/node/get-leaf-inlines-at-range-as-array/nested-with-text-on-every-level.js
  packages/slate/test/models/node/get-leaf-inlines-at-range/multiple-blocks-no-inline.js
  packages/slate/test/models/node/get-leaf-inlines-at-range/multiple-blocks.js
  packages/slate/test/models/node/get-leaf-inlines-at-range/nested-with-text-on-every-level.js
  packages/slate/test/models/node/get-root-blocks-at-range/multiple-blocks.js
  packages/slate/test/models/node/get-root-blocks-at-range/nested-blocks-cursor-in-first-leaf-of-first-parent.js
  packages/slate/test/models/node/get-root-blocks-at-range/nested-blocks-cursor-in-first-leaf-of-second-parent.js
  packages/slate/test/models/node/get-root-blocks-at-range/nested-blocks-cursor-in-second-leaf-of-first-parent.js
  packages/slate/test/models/node/get-root-blocks-at-range/nested-blocks-selection-overlapping-multiple-blocks.js
  packages/slate/test/models/node/get-root-blocks-at-range/nested-blocks-selection-overlapping-texts-in-second-parent.js
  packages/slate/test/models/node/get-root-blocks-at-range/nested-blocks-selection-spanning-first-text.js
  packages/slate/test/models/node/get-root-blocks-at-range/single-block-with-inline.js
  packages/slate/test/models/node/get-root-blocks-at-range/single-block.js
  packages/slate/test/models/node/get-root-blocks-at-range/single-void-block.js
  packages/slate/test/models/node/get-root-inlines-at-range-as-array/multiple-blocks-no-inline.js
  packages/slate/test/models/node/get-root-inlines-at-range-as-array/multiple-blocks.js
  packages/slate/test/models/node/get-root-inlines-at-range-as-array/nested-with-text-on-every-level.js
  packages/slate/test/models/node/get-root-inlines-at-range/multiple-blocks-no-inline.js
  packages/slate/test/models/node/get-root-inlines-at-range/multiple-blocks.js
  packages/slate/test/models/node/get-root-inlines-at-range/nested-with-text-on-every-level.js
Labels: improvement

#2400 Add path type change to changelog entry
  packages/slate/Changelog.md
Labels: docs

#2402 Add optional `id` prop to the `Editor` component
  docs/reference/slate-react/editor.md
  packages/slate-react/src/components/content.js
  packages/slate-react/src/components/editor.js
  packages/slate-react/src/plugins/react.js
Labels: feature

#2401 Add `node.isNodeInRange`
  docs/reference/slate/node.md
  packages/slate/src/interfaces/element.js
  packages/slate/test/models/node/is-node-in-range/block-above-using-key.js
  packages/slate/test/models/node/is-node-in-range/block-above.js
  packages/slate/test/models/node/is-node-in-range/block-below-using-key.js
  packages/slate/test/models/node/is-node-in-range/block-below.js
  packages/slate/test/models/node/is-node-in-range/first-block-inside-using-key.js
  packages/slate/test/models/node/is-node-in-range/first-block-inside.js
  packages/slate/test/models/node/is-node-in-range/first-text-inside-using-key.js
  packages/slate/test/models/node/is-node-in-range/first-text-inside.js
  packages/slate/test/models/node/is-node-in-range/last-block-inside-using-key.js
  packages/slate/test/models/node/is-node-in-range/last-block-inside.js
  packages/slate/test/models/node/is-node-in-range/last-text-inside-using-key.js
  packages/slate/test/models/node/is-node-in-range/last-text-inside.js
  packages/slate/test/models/node/is-node-in-range/text-above-using-key.js
  packages/slate/test/models/node/is-node-in-range/text-above.js
  packages/slate/test/models/node/is-node-in-range/text-below-using-key.js
  packages/slate/test/models/node/is-node-in-range/text-below.js
  packages/slate/test/models/node/is-node-in-range/text-in-middle-inside-using-key.js
  packages/slate/test/models/node/is-node-in-range/text-in-middle-inside.js
Labels: feature

#2403 Do not show placeholder when document contains multiple text nodes
  packages/slate-react/src/plugins/react.js
  packages/slate-react/test/rendering/fixtures/placeholder/multiple-blocks-with-single-empty-text.js
  packages/slate-react/test/rendering/fixtures/placeholder/single-block-with-inline.js
  packages/slate-react/test/rendering/fixtures/placeholder/single-block-with-single-empty-text.js
Labels: bug

#2408 Fix deleteBackwardAtRange removing extra character when called at start of Inline
  packages/slate/src/commands/at-range.js
  packages/slate/test/commands/at-current-range/delete-backward/join-blocks-from-inline.js
Labels: bug

#2412 Fix `renderBlockButton` of rich text example
  examples/rich-text/index.js
Labels: examples

#2426 Fix broken links
  docs/Introduction.md
Labels: docs

#2418 Add `defaultValue` prop to `Editor` component
  examples/check-lists/index.js
  examples/code-highlighting/index.js
  examples/embeds/index.js
  examples/emojis/index.js
  examples/forced-layout/index.js
  examples/huge-document/index.js
  examples/images/index.js
  examples/input-tester/index.js
  examples/markdown-preview/index.js
  examples/markdown-shortcuts/index.js
  examples/paste-html/index.js
  examples/plain-text/index.js
  examples/plugins/index.js
  examples/read-only/index.js
  examples/rtl/index.js
  examples/search-highlighting/index.js
  examples/tables/index.js
  packages/slate-react/src/components/editor.js
Labels: feature

#2441 Add Sanity.io to the list of products
  docs/general/resources.md
Labels: docs
