Repository ianstormtaylor/slate, pull requests merged in 2018-12, with the labels that each got.

#2443 remove react dependency from slate core
  packages/slate/package.json
Labels: bug

#2433 docs: replace change with editor
  docs/reference/slate/commands.md
Labels: docs

#2446 Fix: Do not use experimental array method `flat` in `Versions` example
  examples/versions/index.js
Labels: examples

#2452 Update saving-and-loading-html-content.md
  docs/walkthroughs/saving-and-loading-html-content.md
Labels: docs

#2478 add Netlify CMS to products list
  docs/general/resources.md
Labels: docs

#2462 undo and redo operations are now wrapped with withoutNormalizing call…
  packages/slate/src/commands/on-history.js
Labels: bug

#2469 fix InputEvent global check
  packages/slate-dev-environment/src/index.js
Labels: bug, ⚑ cross platform

#2482 Adding Guilded to Products list
  docs/general/resources.md
Labels: docs

#2483 Adding Prezly to Products list
  docs/general/resources.md
Labels: docs

#2485 fix(docs): correct package's address
  Readme.md
Labels: docs

#2493 fix(schema): previous and child variable may be exactly the same
  packages/slate/src/plugins/schema.js
Labels: bug

#2471 Use weakmap to prevent memory leak and remove indirect __cache__key
  packages/slate/src/utils/memoize.js
Labels: improvement, ⚑ performance

#2491 Update Placeholder to be compatible with older versions of React
  packages/slate-react-placeholder/src/index.js
  packages/slate-react/test/rendering/fixtures/placeholder/single-block-with-single-empty-text.js
Labels: improvement
