Repository ianstormtaylor/slate, pull requests merged in 2018-05, with the labels that each got.

#1731 Remove draggable attribute from void nodes
  packages/slate-react/src/components/void.js
  packages/slate-react/test/rendering/fixtures/custom-block-void.js
  packages/slate-react/test/rendering/fixtures/custom-inline-void.js
Labels: bug

#1803 [examples] fix rich text editor active block logic
  examples/rich-text/index.js
Labels: examples

#1748 [Fix] Copy with empty Block as first-child
  packages/slate-dev-environment/src/index.js
  packages/slate-react/src/utils/clone-fragment.js
Labels: bug, ⚑ waiting

#1802 remove spellcheck force disable on firefox
  packages/slate-react/src/components/content.js
Labels: improvement

#1810 Fix lint problem caused by #1731
  packages/slate-react/src/components/void.js
Labels: bug

#1830 Updated gitignore file
  .gitignore
Labels: debt

#1831 Fix slate-html-serializer: applyMark
  packages/slate-html-serializer/src/index.js
  packages/slate-html-serializer/test/deserialize/mark-void-inline.js
  packages/slate-html-serializer/test/helpers/h.js
Labels: bug

#1825 fix: prevent IE11 from throwing if selection contains tables
  packages/slate-react/src/components/content.js
  packages/slate-react/src/utils/clone-fragment.js
  packages/slate-react/src/utils/remove-all-ranges.js
Labels: bug, ⚑ cross platform

#1832 Add checklist for tests to PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#1808 Optimize getMarks(AtRange), getActiveMarksAtRange, getInsertMarksAtRange, remove the dependency of getCharacters
  packages/slate/src/models/node.js
  packages/slate/src/models/text.js
  packages/slate/src/utils/is-index-in-range.js
Labels: improvement, ⚑ performance

#1815 Set clipboard data programmitcally on copy when supported
  packages/slate-react/src/utils/clone-fragment.js
Labels: debt, improvement, ⚑ cross platform

#1849 Fix invalid ranges in getEventRange
  packages/slate-react/src/utils/get-event-range.js
Labels: bug

#1837 avoid innerText
  packages/slate-react/src/utils/clone-fragment.js
Labels: bug
