Repository ianstormtaylor/slate, pull requests merged in 2018-03, with the labels that each got.

#1704 Add key prop to <br /> elements in html-serializer
  packages/slate-html-serializer/src/index.js
Labels: bug

#1707 Added another editor package built on top of Slate.
  docs/general/resources.md
Labels: docs

#1687 Fix link to auto-markdown example
  Readme.md
Labels: docs

#1689 Handle readOnly inside contentEditable check list
  examples/check-lists/index.js
Labels: examples

#1698 Fix normalize empty inline
  packages/slate/src/constants/core-schema-rules.js
  packages/slate/test/schema/core/preserve-inline-with-empty-void.js
  packages/slate/test/schema/core/remove-nested-empty-inline.js
Labels: bug

#1700 Fix #474
  packages/slate-react/src/utils/offset-key.js
Labels: improvement

#1715 fix applying-custom-formatting.md demo
  docs/walkthroughs/applying-custom-formatting.md
Labels: docs

#1628 Fix skip this in getFurtherstLonelyAncestor
  packages/slate/src/models/node.js
  packages/slate/test/models/index.js
  packages/slate/test/models/node/get-furthest-only-child.js
Labels: bug

#1705 Make serialize/deserialize dev friendlier
  docs/walkthroughs/saving-and-loading-html-content.md
  examples/paste-html/index.js
Labels: docs

#1661 Perhaps faster normalization: Never visit a descendant twice in normalizaton
  packages/slate/benchmark/models/from-json-big.js
  packages/slate/src/changes/with-schema.js
  packages/slate/src/models/node.js
  packages/slate/src/models/text.js
Labels: improvement, ⚑ performance

#1717 Add missing documentation for rule.marks
  docs/reference/slate/schema.md
Labels: docs

#1718 Fix node.isEmpty
  packages/slate/src/constants/core-schema-rules.js
  packages/slate/src/models/block.js
  packages/slate/src/models/document.js
  packages/slate/src/models/inline.js
  packages/slate/src/models/value.js
Labels: bug

#1716 Don't stop propagation of drop event
  packages/slate-react/src/components/content.js
  packages/slate-react/src/plugins/before.js
Labels: bug

#1719 fix: ensure that offset is positive in findDomRange
  packages/slate-react/src/utils/find-dom-point.js
Labels: bug

#1699 Allow null return values, which will skip serializing that node
  packages/slate-html-serializer/src/index.js
  packages/slate-html-serializer/test/serialize/null-rule.js
Labels: feature, ✶ breaking

#1713 Improve memorize interface
  packages/slate/src/models/mark.js
  packages/slate/src/models/node.js
  packages/slate/src/models/schema.js
  packages/slate/src/models/stack.js
  packages/slate/src/models/text.js
  packages/slate/src/utils/memoize.js
Labels: debt, ⚑ performance

#1659 Fix normalize range of the insertTextAtRange
  packages/slate/src/changes/at-range.js
Labels: bug

#1721 Make cache management available in non-dev environment
  packages/slate/src/utils/memoize.js
Labels: improvement

#1728 Fix cloneFragment to work with multiple Editor instances
  packages/slate-react/src/utils/clone-fragment.js
Labels: bug

#1733 fix: Editor[autoFocus] should work, close: #1669
  examples/rich-text/index.js
  packages/slate-react/src/components/content.js
  packages/slate-react/src/components/editor.js
  packages/slate-react/src/plugins/after.js
Labels: bug

#1729 fix: add missing hotkey for delete word backward, close: #1709
  packages/slate-react/src/constants/hotkeys.js
Labels: bug

#1737 Fixed syntax mismatch at normalize method
  docs/reference/slate/schema.md
Labels: docs
