Repository ianstormtaylor/slate, pull requests merged in 2018-07, with the labels that each got.

#1930 Improve and refactor examples
  .eslintrc
  examples/app.js
  examples/check-lists/index.js
  examples/code-highlighting/index.js
  examples/components.js
  examples/embeds/index.js
  examples/emojis/index.js
  examples/forced-layout/index.js
  examples/history/index.js
  examples/hovering-menu/index.js
  examples/huge-document/index.js
  examples/images/index.js
  examples/index.css
  examples/index.js
  examples/links/index.js
  examples/markdown-preview/index.js
  examples/markdown-shortcuts/index.js
  examples/paste-html/index.js
  examples/plain-text/index.js
  examples/plugins/index.js
  examples/read-only/index.js
  examples/rich-text/index.js
  examples/rtl/index.js
  examples/search-highlighting/index.js
  examples/syncing-operations/index.js
  examples/tables/index.js
  package.json
  yarn.lock
Labels: examples

#1942 Added missing paste event handler in slate-simulator docs
  docs/reference/slate-simulator/index.md
Labels: docs

#1950 Add prop "isFocused" / "isSelected" for custom nodes
  docs/reference/slate-react/custom-nodes.md
  examples/embeds/video.js
  examples/emojis/index.js
  examples/images/index.js
  examples/paste-html/index.js
  packages/slate-react/src/components/content.js
  packages/slate-react/src/components/node.js
  packages/slate-react/src/components/void.js
  packages/slate-react/test/rendering/fixtures/blurred-custom-block.js
  packages/slate-react/test/rendering/fixtures/focused-custom-block.js
  packages/slate-react/test/rendering/fixtures/selected-custom-block.js
  packages/slate/src/models/node.js
Labels: improvement, ✶ breaking

#1838 Fix insertFragment: undefined newText
  packages/slate/src/changes/at-current-range.js
Labels: bug

#1953 More tests for `addMarks` and `Leaf.splitLeaves`
  packages/slate/src/models/text.js
  packages/slate/test/changes/at-current-range/add-marks/across-marks.js
  packages/slate/test/changes/at-current-range/add-marks/inside-mark.js
  packages/slate/test/models/index.js
  packages/slate/test/models/leaf/index.js
  packages/slate/test/models/leaf/split-leaves/after-end.js
  packages/slate/test/models/leaf/split-leaves/before-start.js
  packages/slate/test/models/leaf/split-leaves/end.js
  packages/slate/test/models/leaf/split-leaves/middle.js
  packages/slate/test/models/leaf/split-leaves/start.js
  packages/slate/test/models/text/marks/add-marks/to-cover-whole-text.js
Labels: debt

#1958 add null-guard for insertTextAtRange when marks is undefined
  packages/slate/src/changes/at-range.js
Labels: bug

#1968 Added plugin to docs and direct links to NPM and Yarn
  docs/general/plugins.md
Labels: docs

#1973 Added onKeyUp event suppor to slate-simulator and updated docs.
  docs/reference/slate-simulator/index.md
  packages/slate-simulator/src/index.js
Labels: docs, improvement

#1967 Fix drag-and-drop issues in IE11
  packages/slate-react/src/plugins/before.js
  packages/slate-react/src/utils/get-event-range.js
Labels: bug, ⚑ cross platform

#1980 rebuild selection from anchorPath and focusPath if keys were dropped
  packages/slate/src/models/value.js
Labels: improvement

#1976 Fix a missing focus in test
  packages/slate/test/changes/at-current-range/add-marks/across-marks.js
Labels: debt

#1972 Improved slate-simulator docs.
  docs/reference/slate-simulator/index.md
Labels: docs

#1957 plugins reference: update available properties
  docs/reference/slate-react/plugins.md
Labels: docs

#1956 Allow onContextMenu event handler
  packages/slate-react/src/constants/event-handlers.js
Labels: improvement

#1876 Fix #1463: don't split inline tags when wrapping a range in an inline
  packages/slate/src/changes/at-range.js
  packages/slate/test/changes/at-current-range/wrap-inline/inside-inlines-begining.js
  packages/slate/test/changes/at-current-range/wrap-inline/inside-inlines-end.js
  packages/slate/test/changes/at-current-range/wrap-inline/inside-inlines-with-marks.js
  packages/slate/test/changes/at-current-range/wrap-inline/inside-inlines.js
Labels: improvement

#1943 Initial fixes for IE compat of cloneFragment
  docs/general/faq.md
  packages/slate-react/src/utils/clone-fragment.js
Labels: bug, ⚑ cross platform

#1979 allow fromJSON to restore history
  packages/slate/src/models/history.js
  packages/slate/src/models/value.js
Labels: improvement

#1987 Move `insertBlock`s outside of void inlines
  packages/slate/src/changes/at-range.js
  packages/slate/test/changes/at-current-range/insert-block/is-inline-void.js
Labels: bug

#1991 Ensure no deprecate exists in slate-core development
  package.json
  packages/slate-dev-logger/src/index.js
Labels: improvement

#2012 fix getFragmentAtRange to use paths properly
  packages/slate/src/models/node.js
  packages/slate/test/models/node/get-fragment-at-range.js
Labels: bug

#2010 Add slate-react to the bundled source guide
  docs/walkthroughs/using-the-bundled-source.md
Labels: docs
