Repository ianstormtaylor/slate, pull requests merged in 2018-02, with the labels that each got.

#1621 Fix drag and dropping an inline node "forward" in the document
  packages/slate-react/src/plugins/after.js
Labels: bug

#1630 Remove redundant memoization
  packages/slate/src/models/node.js
Labels: improvement, ⚑ performance

#1645 Fixing the bug that getMarks steals mark from the previous block
  packages/slate/src/models/node.js
Labels: bug

#1644 Replace zero width blocks with newline before copy
  packages/slate-react/src/components/leaf.js
  packages/slate-react/src/utils/clone-fragment.js
  packages/slate-react/src/utils/find-point.js
  packages/slate-react/test/rendering/fixtures/custom-block-void.js
  packages/slate-react/test/rendering/fixtures/custom-inline-multiple.js
  packages/slate-react/test/rendering/fixtures/custom-inline-void.js
  packages/slate-react/test/rendering/fixtures/custom-inline.js
  packages/slate-react/test/rendering/fixtures/default-block-with-inline.js
  packages/slate-react/test/rendering/fixtures/empty-block-with-inline.js
  packages/slate-react/test/rendering/fixtures/empty-block.js
  packages/slate-react/test/rendering/fixtures/readonly-custom-inline-void.js
Labels: bug

#1643 Fix marks of undefined on char.marks
  packages/slate/src/models/node.js
Labels: bug

#1637 Update plugins used in plugins example
  package.json
  yarn.lock
Labels: examples

#1631 Use pageXOffset instead of scrollX in hover menu example
  examples/hovering-menu/index.js
Labels: examples, ⚑ cross platform

#1647 Fix for text value being null in an onDrop event
  packages/slate-react/src/plugins/after.js
Labels: bug

#1642 Set up webpack configuration for building examples
  .babelrc
  .gitignore
  examples/Readme.md
  examples/app.js
  examples/dev.html
  examples/hovering-menu/index.js
  examples/index.html
  examples/index.js
  examples/test.html
  package.json
  rollup.config.js
  support/rollup/examples.js
  support/webpack.config.js
  yarn.lock
Labels: examples

#1665 Add back babel-cli as a development dependency.
  package.json
  yarn.lock
Labels: bug

#1558 Convert setBlock and setInline to plurals for more intuitive naming.
  docs/reference/slate/change.md
  docs/walkthroughs/applying-custom-formatting.md
  docs/walkthroughs/defining-custom-block-nodes.md
  examples/check-lists/index.js
  examples/markdown-shortcuts/index.js
  examples/rich-text/index.js
  packages/slate/src/changes/at-current-range.js
  packages/slate/src/changes/at-range.js
  packages/slate/test/changes/at-current-range/set-block/across-blocks.js
  packages/slate/test/changes/at-current-range/set-block/across-inlines.js
  packages/slate/test/changes/at-current-range/set-block/data-only.js
  packages/slate/test/changes/at-current-range/set-block/hanging-selection.js
  packages/slate/test/changes/at-current-range/set-block/nested-block.js
  packages/slate/test/changes/at-current-range/set-block/single-block-string-shorthand.js
  packages/slate/test/changes/at-current-range/set-block/single-block.js
  packages/slate/test/changes/at-current-range/set-block/with-data-as-map.js
  packages/slate/test/changes/at-current-range/set-block/with-data-as-object.js
  packages/slate/test/changes/at-current-range/set-block/with-is-void.js
  packages/slate/test/changes/at-current-range/set-inline/across-inlines.js
  packages/slate/test/changes/at-current-range/set-inline/data-only.js
  packages/slate/test/changes/at-current-range/set-inline/nested-inline.js
  packages/slate/test/changes/at-current-range/set-inline/single-inline-string-shorthand.js
  packages/slate/test/changes/at-current-range/set-inline/single-inline.js
  packages/slate/test/changes/at-current-range/set-inline/with-data-object.js
  packages/slate/test/changes/at-current-range/set-inline/with-data.js
  packages/slate/test/changes/at-current-range/set-inline/with-is-void.js
Labels: debt, ✶ breaking

#1663 remove the void text content restriction, closes #1504
  packages/slate-plain-serializer/test/serialize/block-with-is-void.js
  packages/slate-plain-serializer/test/serialize/inline-with-is-void.js
  packages/slate-react/src/components/leaf.js
  packages/slate/src/changes/at-range.js
  packages/slate/src/constants/core-schema-rules.js
  packages/slate/src/models/node.js
  packages/slate/test/changes/at-current-range/delete-backward/empty-after-void-block.js
  packages/slate/test/changes/at-current-range/delete-forward/empty-before-void-block.js
  packages/slate/test/changes/at-current-range/delete/non-void-block-as-first-with-void-siblings-only-non-void.js
  packages/slate/test/changes/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-up-to-start-of-void.js
  packages/slate/test/changes/at-current-range/delete/non-void-block-as-first-with-void-siblings-partially-non-void-and-void.js
  packages/slate/test/changes/at-current-range/delete/void-block-as-first-with-non-void-siblings-select-void-end-and-next-word.js
  packages/slate/test/changes/at-current-range/delete/void-blocks-as-first-with-non-void-siblings-only-first-void.js
  packages/slate/test/changes/at-current-range/delete/void-inline-as-first-with-non-void-sibling.js
  packages/slate/test/changes/at-current-range/insert-block/is-void-end.js
  packages/slate/test/changes/at-current-range/insert-block/is-void-start.js
  packages/slate/test/changes/at-current-range/insert-inline/block-end.js
  packages/slate/test/changes/at-current-range/insert-inline/block-middle.js
  packages/slate/test/changes/at-current-range/insert-inline/block-start.js
  packages/slate/test/changes/at-current-range/insert-inline/inline-middle.js
  packages/slate/test/changes/at-current-range/insert-inline/is-empty.js
  packages/slate/test/changes/at-current-range/insert-inline/with-inline.js
  packages/slate/test/changes/at-current-range/set-block/with-is-void.js
  packages/slate/test/changes/at-current-range/set-inline/with-is-void.js
  packages/slate/test/changes/by-key/remove-text-by-key/inline-void.js
  packages/slate/test/changes/by-key/set-node-by-key/inline-with-is-void.js
  packages/slate/test/changes/general/call/call-no-arguments.js
  packages/slate/test/changes/general/call/call-with-arguments.js
  packages/slate/test/schema/custom/node-is-void-invalid-default.js
  packages/slate/test/serializers/raw/deserialize/block-with-is-void.js
  packages/slate/test/serializers/raw/deserialize/inline-with-is-void.js
  packages/slate/test/serializers/raw/serialize/block-with-is-void.js
  packages/slate/test/serializers/raw/serialize/inline-with-is-void.js
Labels: feature, improvement, ✶ breaking

#1666 Use source-map-loader for more fine-grained sourcemaps.
  package.json
  support/rollup/factory.js
  support/webpack/config.js
  yarn.lock
Labels: improvement
