Repository ianstormtaylor/slate, pull requests merged in 2018-09, with the labels that each got.

#2150 fix(content): attach the right `onNativeSelectionChange`.
  packages/slate-react/src/components/content.js
Labels: bug

#2151 Add support for validating functions inside schema's rules
  docs/reference/slate/schema.md
  packages/slate/src/models/schema.js
  packages/slate/test/schema/custom/child-kind-invalid-function.js
  packages/slate/test/schema/custom/child-type-invalid-function.js
  packages/slate/test/schema/custom/first-child-kind-invalid-function.js
  packages/slate/test/schema/custom/first-child-type-invalid-function.js
  packages/slate/test/schema/custom/last-child-kind-invalid-function.js
  packages/slate/test/schema/custom/last-child-type-invalid-function.js
  packages/slate/test/schema/custom/next-kind-invalid-custom.js
  packages/slate/test/schema/custom/next-kind-invalid-default.js
  packages/slate/test/schema/custom/next-kind-invalid-function.js
  packages/slate/test/schema/custom/next-type-invalid-custom.js
  packages/slate/test/schema/custom/next-type-invalid-default.js
  packages/slate/test/schema/custom/next-type-invalid-function.js
  packages/slate/test/schema/custom/node-data-invalid-function.js
  packages/slate/test/schema/custom/node-mark-invalid-function.js
  packages/slate/test/schema/custom/node-object-invalid-function.js
  packages/slate/test/schema/custom/node-type-invalid-function.js
  packages/slate/test/schema/custom/parent-kind-invalid-function.js
  packages/slate/test/schema/custom/parent-type-invalid-function.js
  packages/slate/test/schema/custom/previous-kind-invalid-custom.js
  packages/slate/test/schema/custom/previous-kind-invalid-default.js
  packages/slate/test/schema/custom/previous-kind-invalid-function.js
  packages/slate/test/schema/custom/previous-type-invalid-custom.js
  packages/slate/test/schema/custom/previous-type-invalid-default.js
  packages/slate/test/schema/custom/previous-type-invalid-function.js
Labels: feature

#2161 docs(change.md): correct `setOperationFlag()` signature
  docs/reference/slate/change.md
Labels: docs

#2163 Avoid crash in updateSelection() in editor when getSelection() is null
  packages/slate-react/src/components/content.js
Labels: bug

#2175 fix(example/links): a few fixes for the links example
  examples/links/index.js
Labels: examples

#2179 Fix deprecated .move > .moveForward in the after plugin
  packages/slate-react/src/plugins/after.js
Labels: bug

#2158 Fix marks being cleared on selection events
  packages/slate-react/src/plugins/after.js
Labels: bug

#2178 Gracefully handle permission denied error in FF when checking for element.nodeType
  packages/slate-react/src/components/content.js
Labels: bug

#2181 Actually fix marks being cleared on selection events
  packages/slate-react/src/plugins/after.js
Labels: bug

#2183 debt(codecov): disable code coverage in builds
  .travis.yml
Labels: debt

#2185 Updating function in readme.md
  docs/walkthroughs/saving-and-loading-html-content.md
Labels: docs

#2186 Codecov: Only test slate, slate-html-serializer and slate-plain-serializer
  .nycrc
  .travis.yml
Labels: debt

#2193 refactor normalization to be operations-based
  docs/guides/schemas.md
  docs/reference/slate/change.md
  docs/reference/slate/schema.md
  examples/search-highlighting/index.js
  packages/slate-react/src/plugins/before.js
  packages/slate/Changelog.md
  packages/slate/src/changes/at-range.js
  packages/slate/src/changes/by-path.js
  packages/slate/src/changes/index.js
  packages/slate/src/changes/on-history.js
  packages/slate/src/changes/on-value.js
  packages/slate/src/changes/with-schema.js
  packages/slate/src/interfaces/element.js
  packages/slate/src/models/change.js
  packages/slate/src/models/history.js
  packages/slate/src/models/operation.js
  packages/slate/src/models/value.js
  packages/slate/src/utils/path-utils.js
  packages/slate/test/changes/by-key/insert-node-by-key/inline.js
  packages/slate/test/history/undo/move-node-before-itself.js
  packages/slate/test/index.js
  packages/slate/test/models/change/without-normalization-normalize-flag-false.js
  packages/slate/test/models/change/without-normalization-normalize-flag-true.js
  packages/slate/test/models/change/without-normalization-option-override.js
  packages/slate/test/models/change/without-normalization.js
  packages/slate/test/schema/custom/child-unknown-custom.js
Labels: improvement, ✶ breaking

#2197 Merge decorations from multiple plugins
  packages/slate/src/interfaces/element.js
Labels: bug

#2198 Normalize copying void inline nodes
  packages/slate-react/src/components/content.js
Labels: bug

#2204 Update resources with Chatterslate
  docs/general/resources.md
Labels: docs

#2207 Update products to include Cake
  docs/general/resources.md
Labels: docs

#2205 Add a version example
  examples/app.js
  examples/versions/index.js
Labels: examples

#2057 docs(plugins): update signature docs
  docs/reference/slate-react/plugins.md
Labels: docs
