Repository ianstormtaylor/slate, pull requests merged in 2018-08, with the labels that each got.

#2008 Add Products: Taskade
  docs/general/resources.md
Labels: docs

#2020 Docs: Remove leading semicolon in code snippet
  docs/guides/changes.md
Labels: docs

#2021 Refactor tests
  .eslintrc
  package.json
  packages/slate-dev-benchmark/package.json
  packages/slate-dev-environment/package.json
  packages/slate-dev-logger/package.json
  packages/slate-dev-test-utils/Readme.md
  packages/slate-dev-test-utils/package.json
  packages/slate-dev-test-utils/src/index.js
  packages/slate-dev-test-utils/test/index.js
  packages/slate-html-serializer/test/index.js
  packages/slate-hyperscript/test/index.js
  packages/slate-plain-serializer/test/index.js
  packages/slate-react/test/index.js
  packages/slate-react/test/plugins/index.js
  packages/slate-react/test/rendering/index.js
  packages/slate-react/test/utils/get-children-decorations.js
  packages/slate-react/test/utils/index.js
  packages/slate/package.json
  packages/slate/test/changes/index.js
  packages/slate/test/helpers/h.js
  packages/slate/test/history/index.js
  packages/slate/test/index.js
  packages/slate/test/models/index.js
  packages/slate/test/models/leaf/index.js
  packages/slate/test/models/node/get-fragment-at-range.js
  packages/slate/test/models/node/get-fragment-at-range/block-across.js
  packages/slate/test/models/node/get-fragment-at-range/block.js
  packages/slate/test/models/node/get-furthest-only-child.js
  packages/slate/test/models/node/get-furthest-only-child/block-nested.js
  packages/slate/test/models/node/get-furthest-only-child/block.js
  packages/slate/test/models/node/get-furthest-only-child/inline.js
  packages/slate/test/models/node/get-furthest-only-child/text-nested.js
  packages/slate/test/models/node/get-furthest-only-child/text.js
  packages/slate/test/models/text/index.js
  packages/slate/test/operations/index.js
  packages/slate/test/schema/index.js
  packages/slate/test/serializers/index.js
  packages/slate/test/serializers/raw/serialize/preserve-keys.js
  packages/slate/test/serializers/raw/serialize/preserve-selection-and-keys.js
Labels: debt

#2023 fix selection operations being duplicated
  examples/app.js
  packages/slate-react/src/plugins/after.js
  packages/slate-react/src/utils/find-range.js
  packages/slate/src/changes/on-selection.js
Labels: bug

#2025 add `Node.createRange` for range resolution
  packages/slate-react/src/plugins/after.js
  packages/slate-react/src/utils/find-range.js
  packages/slate-react/src/utils/get-event-range.js
  packages/slate/src/changes/by-path.js
  packages/slate/src/changes/on-selection.js
  packages/slate/src/models/document.js
  packages/slate/src/models/node.js
  packages/slate/src/models/value.js
Labels: improvement

#2026 fix range offset defaults to be `null`
  packages/slate/src/models/range.js
Labels: improvement, ✶ breaking

#2027 change `isBackward` to be computed from paths
  packages/slate-hyperscript/test/fixtures/cursor-across-block.js
  packages/slate-hyperscript/test/fixtures/cursor-across-blocks-and-inlines.js
  packages/slate-hyperscript/test/fixtures/cursor-across-blocks-end.js
  packages/slate-hyperscript/test/fixtures/cursor-across-blocks-middle.js
  packages/slate-hyperscript/test/fixtures/cursor-across-blocks-start.js
  packages/slate-hyperscript/test/fixtures/cursor-across-multiple-blocks-end.js
  packages/slate-hyperscript/test/fixtures/cursor-across-multiple-blocks-middle.js
  packages/slate-hyperscript/test/fixtures/cursor-across-multiple-blocks-start.js
  packages/slate-hyperscript/test/fixtures/cursor-block-end.js
  packages/slate-hyperscript/test/fixtures/cursor-block-middle.js
  packages/slate-hyperscript/test/fixtures/cursor-block-start.js
  packages/slate-hyperscript/test/fixtures/cursor-custom-block-middle.js
  packages/slate-hyperscript/test/fixtures/cursor-inline.js
  packages/slate-hyperscript/test/fixtures/decoration.js
  packages/slate-hyperscript/test/fixtures/selection.js
  packages/slate/src/changes/at-range.js
  packages/slate/src/models/operation.js
  packages/slate/src/models/range.js
  packages/slate/src/models/value.js
  packages/slate/src/utils/path-utils.js
  packages/slate/test/serializers/raw/serialize/preserve-selection-and-keys.js
  packages/slate/test/serializers/raw/serialize/preserve-selection.js
Labels: improvement, ✶ breaking

#2016 Remove the deprecated Character model, and methods that reference it
  docs/Readme.md
  docs/reference/slate-prop-types/index.md
  docs/reference/slate/character.md
  docs/reference/slate/mark.md
  docs/reference/slate/node.md
  docs/reference/slate/text.md
  docs/reference/slate/value.md
  packages/slate-prop-types/src/index.js
  packages/slate/src/constants/model-types.js
  packages/slate/src/index.js
  packages/slate/src/models/character.js
  packages/slate/src/models/leaf.js
  packages/slate/src/models/node.js
  packages/slate/src/models/text.js
  packages/slate/src/models/value.js
Labels: debt, ✶ breaking

#2048 refactor slate-hotkeys, fix deleting at start of block
  packages/slate-hotkeys/Changelog.md
  packages/slate-hotkeys/package.json
  packages/slate-hotkeys/src/index.js
  packages/slate-react/src/plugins/after.js
  packages/slate-react/src/plugins/before.js
  yarn.lock
Labels: bug, debt

#2053 fix pointForward and pointBackward
  packages/slate/src/changes/on-selection.js
  yarn.lock
Labels: bug

#2063 refactor native beforeinput handling
  packages/slate-dev-environment/src/index.js
  packages/slate-react/src/components/content.js
  packages/slate-react/src/plugins/after.js
  packages/slate-react/src/plugins/before.js
Labels: debt

#2068 Add input tester example
  examples/app.js
  examples/input-tester/index.js
  examples/input-tester/value.json
  package.json
  yarn.lock
Labels: examples

#2052 Do not use requestAnimation if DataTransfer is available
  packages/slate-react/src/plugins/after.js
  packages/slate-react/src/utils/clone-fragment.js
Labels: improvement

#2083 fix schema defaultNormalize to use normalize:false
  packages/slate/src/models/schema.js
Labels: bug

#2074 [hyperscript] rename decorators option in params to decorations
  Readme.md
  docs/Introduction.md
  examples/Readme.md
  examples/markdown-preview/index.js
  packages/slate-hyperscript/src/index.js
  packages/slate-hyperscript/test/decorations/across-blocks.js
  packages/slate-hyperscript/test/decorations/across-marks.js
  packages/slate-hyperscript/test/decorations/deep-anchors.js
  packages/slate-hyperscript/test/decorations/intersecting-marks.js
  packages/slate-hyperscript/test/decorations/multiple.js
  packages/slate-hyperscript/test/decorations/nested.js
  packages/slate-hyperscript/test/decorations/overlapping.js
  packages/slate-hyperscript/test/fixtures/decoration-across-blocks.js
  packages/slate-hyperscript/test/fixtures/decoration.js
  packages/slate/test/helpers/h.js
Labels: debt, ✶ breaking

#1975 Upgrade to React v16 lifecycle
  package.json
  packages/slate-react/package.json
  packages/slate-react/src/components/content.js
  packages/slate-react/src/components/editor.js
  packages/slate-react/src/components/node.js
  packages/slate-react/src/plugins/after.js
  yarn.lock
Labels: debt

#2089 Fix key duplication warning and deprecation in benchmark
  benchmark/slate-react/rendering/decoration.js
  benchmark/slate/changes/add-mark.js
  benchmark/slate/changes/insert-node-by-key.js
  benchmark/slate/changes/insert-text.js
  benchmark/slate/changes/normalize.js
  benchmark/slate/changes/split-block.js
  benchmark/slate/models/get-active-marks-at-range.js
  benchmark/slate/models/get-blocks-at-range.js
  benchmark/slate/models/get-inlines-at-range.js
  benchmark/slate/models/get-marks-at-range.js
  benchmark/slate/models/get-texts-at-range.js
Labels: debt

#2080 Introduce Range.updatePoints
  packages/slate/src/models/range.js
  packages/slate/src/models/value.js
Labels: improvement

#2087 IE11 html serializer parser fix
  packages/slate-html-serializer/src/index.js
Labels: bug, ⚑ cross platform

#2091 fix images example schema
  examples/images/index.js
Labels: examples

#2102 deprecate isVoid and related properties/methods
  docs/guides/schemas.md
  examples/hovering-menu/index.js
  package.json
  packages/slate-react/src/components/leaf.js
  packages/slate-react/src/components/node.js
  packages/slate-react/src/plugins/after.js
  packages/slate-react/src/plugins/before.js
  packages/slate-react/src/utils/clone-fragment.js
  packages/slate-react/src/utils/get-event-range.js
  packages/slate/src/changes/at-range.js
  packages/slate/src/changes/on-selection.js
  packages/slate/src/models/block.js
  packages/slate/src/models/document.js
  packages/slate/src/models/inline.js
  packages/slate/src/models/node.js
  packages/slate/src/models/operation.js
  packages/slate/src/models/schema.js
  packages/slate/src/models/value.js
Labels: improvement, ✶ breaking

#2090 use fragment instead of node transfer type on drag
  packages/slate-react/src/plugins/after.js
  packages/slate/src/changes/at-range.js
Labels: bug

#2120 small typo and broken link for range doc fixed
  docs/guides/changes.md
Labels: docs

#2122 Fix incorrect history stack
  packages/slate/src/changes/on-selection.js
  yarn.lock
Labels: bug

#2131 fix(content): use handlers that actually exist in event listeners
  packages/slate-react/src/components/content.js
Labels: bug
