Repository ianstormtaylor/slate, pull requests merged in 2018-06, with the labels that each got.

#1880 Enable insert in the start of table cell
  examples/tables/index.js
Labels: examples

#1875 InsertTextAtRange normalize
  packages/slate/src/changes/at-range.js
  packages/slate/test/changes/at-current-range/insert-text/expanded-with-mark.js
Labels: bug

#1846 Fix a hyperscript bug in perserving text-key
  packages/slate-hyperscript/src/index.js
  packages/slate-hyperscript/test/default/perserve-keys-in-right-text.js
  packages/slate-hyperscript/test/index.js
Labels: bug

#1864 Fix the characters count in deleteForward
  packages/slate/src/changes/at-range.js
  packages/slate/test/changes/at-current-range/delete-line-backward/text-start.js
  packages/slate/test/changes/at-current-range/delete-line-forward/inline-middle-emoji.js
  packages/slate/test/changes/at-current-range/delete-line-forward/inline-multi-voids.js
  packages/slate/test/changes/at-current-range/delete-line-forward/inline-void-end.js
  packages/slate/test/changes/at-current-range/delete-line-forward/text-end.js
  packages/slate/test/changes/at-current-range/delete-line-forward/text-start.js
  packages/slate/test/changes/at-current-range/delete-line-forward/word-middle.js
Labels: bug

#1863 [fix/html-serializer-docs-add-class-name-example] add example to the …
  docs/walkthroughs/saving-and-loading-html-content.md
Labels: docs

#1865 Use cleaned up text content when copying into plain/text
  packages/slate-react/src/utils/clone-fragment.js
Labels: bug

#1889 fix release building process for umds
  package.json
Labels: bug

#1886 Inline Void block cursor
  packages/slate-react/src/components/void.js
  packages/slate-react/test/rendering/fixtures/custom-inline-void.js
Labels: bug

#1847 Perhaps Faster stack
  packages/slate/src/models/stack.js
Labels: improvement

#1893 [docs] A handful of grammar nits in the docs
  docs/guides/data-model.md
  docs/guides/schemas.md
  docs/reference/slate-react/core-plugins.md
  docs/reference/slate-react/editor.md
  docs/reference/slate/schema.md
  docs/walkthroughs/saving-and-loading-html-content.md
  docs/walkthroughs/saving-to-a-database.md
  docs/walkthroughs/using-plugins.md
Labels: docs

#1898 [docs] add Change.normalize into the docs, add some caveats about perf
  docs/reference/slate/change.md
Labels: docs

#1839 update schema customizer to merge marks
  packages/slate/src/models/schema.js
Labels: improvement

#1869 Allow user to use immutable 4.0.0-rc without yarn warning
  packages/slate-html-serializer/package.json
  packages/slate-plain-serializer/package.json
  packages/slate-prop-types/package.json
  packages/slate-react/package.json
  packages/slate/package.json
Labels: debt

#1901 Fix issue with pasting in IE11
  packages/slate-react/src/utils/get-event-transfer.js
Labels: bug, ⚑ cross platform

#1899 [slate-react] Pass renderEditor prop through into editor plugin
  packages/slate-react/src/constants/plugin-props.js
Labels: bug

#1778 Operations update decorations
  examples/search-highlighting/index.js
  packages/slate-hyperscript/src/index.js
  packages/slate/src/models/range.js
  packages/slate/src/models/value.js
  packages/slate/src/operations/apply.js
  packages/slate/test/helpers/h.js
  packages/slate/test/operations/apply/update-decorations/atomic-invalidation-delete.js
  packages/slate/test/operations/apply/update-decorations/atomic-invalidation-insert.js
  packages/slate/test/operations/apply/update-decorations/delete-before.js
  packages/slate/test/operations/apply/update-decorations/insert-before.js
  packages/slate/test/operations/apply/update-decorations/merge-node.js
  packages/slate/test/operations/apply/update-decorations/remove-node.js
  packages/slate/test/operations/index.js
  packages/slate/test/serializers/raw/serialize/preserve-selection-and-keys.js
  packages/slate/test/serializers/raw/serialize/preserve-selection.js
Labels: bug, improvement

#1917 fix removeText with Mark of length 1
  packages/slate/src/models/text.js
  packages/slate/test/models/text/delete/inside-a-leaf/delete-a-char-with-mark.js
Labels: bug

#1921 Fix typo in Docs
  docs/reference/slate/change.md
Labels: docs

#1910 [core/models] add replaceMark method on Change, tests, docs
  docs/reference/slate/change.md
  packages/slate/src/changes/at-current-range.js
  packages/slate/test/changes/at-current-range/replace-mark/across-blocks.js
  packages/slate/test/changes/at-current-range/replace-mark/across-inlines.js
  packages/slate/test/changes/at-current-range/replace-mark/collapsed-selection.js
  packages/slate/test/changes/at-current-range/replace-mark/existing-marks.js
  packages/slate/test/changes/at-current-range/replace-mark/first-character.js
  packages/slate/test/changes/at-current-range/replace-mark/last-character.js
  packages/slate/test/changes/at-current-range/replace-mark/middle-character.js
  packages/slate/test/changes/at-current-range/replace-mark/whole-word.js
  packages/slate/test/changes/at-current-range/replace-mark/with-mark-object.js
  packages/slate/test/changes/at-current-range/replace-mark/with-plain-object.js
Labels: feature

#1928 Fix a linter bug in a semi-colon case
  .eslintrc
  packages/slate-react/src/utils/clone-fragment.js
Labels: debt

#1929 fix(DragAndDrop): isDraggingInternally should not be reset by the onDragOver handler
  packages/slate-react/src/plugins/after.js
Labels: bug

#1927 fix(Safari): Set a text value in dataTransfer to have the cursor on Safari when dragging a text node
  packages/slate-react/src/utils/set-event-transfer.js
Labels: bug, ⚑ cross platform
