Repository ianstormtaylor/slate, pull requests merged in 2019-08, with the labels that each got.

#2914 Add point normalization to addAnnotation.
  packages/slate/src/models/value.js
Labels: bug

#2915 Add annotation-related ops to path.transform. (#2)
  packages/slate/src/utils/path-utils.js
Labels: bug

#2236 fix(firefox): fixed the bug that happens when changing the focus from one field to another
  packages/slate-react/src/components/content.js
Labels: bug, ⚑ cross platform

#2925 fix: Unknown event handler property `onEvent`
  packages/slate-react/src/components/content.js
Labels: bug

#2934 Fix renderBlock() in paste-html example
  examples/paste-html/index.js
Labels: examples

#2946 Fix undo a removeMark re-add mark to wrong nodes
  packages/slate/src/commands/by-path.js
  packages/slate/test/history/undo/toggle-mark.js
Labels: bug

#2938 Fix splitNode range update when selection is backward
  packages/slate/src/models/value.js
  packages/slate/test/commands/at-current-range/remove-mark/part-of-mark-backward.js
  packages/slate/test/commands/at-current-range/remove-mark/part-of-mark.js
Labels: bug

#2559 Mutate newDirtyPaths instead of creating a new array every iteration
  packages/slate/src/controllers/editor.js
Labels: improvement, ⚑ performance

#2964 Update glossary.md with definition of `match`
  docs/general/glossary.md
Labels: docs

#2920 fixed #1237 which calls Selection.getRangeAt(0) when Selection.type = 'None'
  packages/slate-react/src/components/content.js
Labels: bug

#2916 Deduplicate dirty paths for normalization.
  packages/slate/src/controllers/editor.js
Labels: improvement, ⚑ performance

#2918 Fix rendering of collapsed annotation at offset zero.
  packages/slate/src/models/text.js
Labels: bug

#2975 Update installing-slate.md
  docs/walkthroughs/installing-slate.md
Labels: docs

#2966 deleteBackwardAtRange now works when offset is equal to n
  packages/slate/src/commands/at-range.js
  packages/slate/test/commands/at-range/delete-backward-at-range/from-offset.js
Labels: bug

#2971 Fix range normalization for node removal and split.
  packages/slate/src/models/value.js
Labels: bug

#2970 Fix extracting relative ranges from decorations.
  packages/slate-react/src/components/node.js
Labels: bug

#2974 fix React warnings on renderMark, renderBlock, renderDecoration
  packages/slate-react/src/components/editor.js
  packages/slate-react/src/constants/other-handlers.js
Labels: bug

#2948 Fix several undo/redo issues related to selection operation
  packages/slate-react/src/components/content.js
  packages/slate/src/commands/on-history.js
Labels: bug
