Repository ianstormtaylor/slate, pull requests merged in 2019-01, with the labels that each got.

#2450 feat(Examples): improve example navigation
  examples/app.js
Labels: examples

#2553 Android 8.0, 8.1 and 9.0 Support
  examples/app.js
  examples/composition/index.js
  examples/composition/insert.js
  examples/composition/special.js
  examples/composition/split-join.js
  examples/composition/util.js
  examples/composition/value.json
  package.json
  packages/slate-react/src/components/content.js
  packages/slate-react/src/plugins/ANDROID.md
  packages/slate-react/src/plugins/android.js
  packages/slate-react/src/plugins/debug.js
  packages/slate-react/src/plugins/dom.js
  packages/slate-react/src/utils/android-api-version.js
  packages/slate-react/src/utils/closest.js
  packages/slate-react/src/utils/element-snapshot.js
  packages/slate-react/src/utils/executor.js
  packages/slate-react/src/utils/fix-selection-in-zero-width-block.js
  packages/slate-react/src/utils/get-selection-from-dom.js
  packages/slate-react/src/utils/is-input-data-enter.js
  packages/slate-react/src/utils/is-input-data-last-char.js
  packages/slate-react/src/utils/set-selection-from-dom.js
  packages/slate-react/src/utils/set-text-from-dom-node.js
  packages/slate-react/src/utils/slate-snapshot.js
Labels: bug, examples, feature, improvement, ⚑ ime, ⚑ mobile

#2497 Update link to source
  docs/Introduction.md
Labels: docs

#2286 Clarify children access in renderEditor in docs
  docs/reference/slate-react/plugins.md
Labels: docs, ⚑ waiting

#2555 move_node tests and code clean up
  packages/slate/src/commands/by-path.js
  packages/slate/src/interfaces/element.js
  packages/slate/src/operations/invert.js
  packages/slate/test/commands/by-path/move-node-by-path/new-path-exists.js
  packages/slate/test/commands/by-path/move-node-by-path/new-sibling-is-text-node.js
  packages/slate/test/commands/by-path/move-node-by-path/path-left-sibling-of-new-path-ancestor.js
  packages/slate/test/commands/by-path/move-node-by-path/sibling-swap.js
  packages/slate/test/commands/by-path/move-node-by-path/text-nodes.js
  packages/slate/test/history/undo/move-node-by-path-ancestor-left-sibling.js
  packages/slate/test/history/undo/move-node-by-path.js
Labels: bug, debt

#2498 fix(at-range): correct `findInsertionNode` method throw a type error …
  packages/slate/src/commands/at-range.js
  packages/slate/test/commands/at-current-range/insert-fragment/fragment-single-child-block.js
Labels: bug

#2536 Fix dirty path normalization on move_node
  packages/slate/src/utils/path-utils.js
  packages/slate/test/commands/at-current-range/delete-backward/join-nested-blocks-different-depth.js
  packages/slate/test/history/undo/delete-backward-nested-blocks.js
  packages/slate/test/history/undo/delete-backward.js
Labels: bug

#2535 Fix mouse refocus in IE 11
  packages/slate-react/src/plugins/after.js
Labels: bug, ⚑ cross platform

#2526 Prevent default browser scroll on content focus
  packages/slate-react/src/components/content.js
Labels: bug

#2496 Use `babel-polyfill` in place of `polyfill.io` CDN
  package.json
  support/webpack/config.js
  yarn.lock
Labels: debt, examples

#2460 Improve slate-react-placeholder component.
  packages/slate-react-placeholder/src/index.js
Labels: bug

#2569 Fix benchmarks that use value.change
  benchmark/slate-react/index.js
  benchmark/slate-react/rendering/decoration.js
  benchmark/slate-react/rendering/large-with-selection.js
  benchmark/slate/changes/add-mark.js
  benchmark/slate/changes/delete-backward.js
  benchmark/slate/changes/delete-forward.js
  benchmark/slate/changes/insert-node-by-key.js
  benchmark/slate/changes/insert-text-by-key.js
  benchmark/slate/changes/insert-text.js
  benchmark/slate/changes/normalize.js
  benchmark/slate/changes/remove-node-by-key.js
  benchmark/slate/changes/set-blocks.js
  benchmark/slate/changes/split-block.js
  benchmark/slate/models/get-active-marks-at-range.js
  benchmark/slate/models/get-leaf-blocks-at-range.js
  benchmark/slate/models/get-leaf-inlines-at-range.js
  benchmark/slate/models/get-marks-at-range.js
  benchmark/slate/models/get-texts-at-range.js
  packages/slate-dev-benchmark/src/Bench.js
Labels: debt
