Repository ianstormtaylor/slate, pull requests merged in 2019-11, with the labels that each got.

#3062 Removed 404 links from Changelog.md
  Changelog.md
Labels: docs

#3064 Update saving-and-loading-html-content.md
  docs/walkthroughs/saving-and-loading-html-content.md
Labels: docs

#3070 fixing paste html example
  examples/paste-html/index.js
Labels: examples

#3072 Fix when clear search text, all text split by blank
  examples/search-highlighting/index.js
Labels: examples

#3083 Change renderNode docs to renderBlock and renderInline
  docs/guides/rendering.md
Labels: docs

#3085 Include data and type when converting set_annotation to JS
  packages/slate/src/models/operation.js
Labels: bug

#3079 Simplify the mentions example
  examples/mentions/Suggestions.js
  examples/mentions/index.js
  examples/mentions/value.json
Labels: examples

#3110 Add redo hotkey for Windows (Ctrl+Shift+Z)
  packages/slate-hotkeys/src/index.js
Labels: improvement

#3156 Fix variable name in docs
  docs/walkthroughs/06-saving-to-a-database.md
Labels: docs

#3153 Remove controlled value state from docs
  docs/walkthroughs/05-executing-commands.md
Labels: docs

#3149 Nodejs 13 compat and eslint/prettier glob fix
  config/babel/babel.config.cjs
  config/babel/register.cjs
  config/rollup/rollup.config.js
  package.json
  site/next.config.cjs
Labels: debt

#3159 Update contributors.md to discuss repo setup
  Contributing.md
Labels: docs

#3158 improve prop typings for Editable
  packages/slate-react/src/components/editable.tsx
Labels: bug

#3160 lint & example fixes
  .eslintignore
  .eslintrc
  Contributing.md
  docs/Summary.md
  package.json
  packages/slate-history/package.json
  packages/slate-hyperscript/package.json
  packages/slate-react/package.json
  packages/slate-schema/package.json
  packages/slate/package.json
  site/next.config.js
Labels: debt

#3169 Update Adding Event Handlers walkthrough
  docs/walkthroughs/02-adding-event-handlers.md
Labels: examples

#3176 fix: lost redos when trigger set_selection (fix #3140)
  packages/slate-history/src/with-history.ts
Labels: bug
