Repository ianstormtaylor/slate, pull requests merged in 2019-12, with the labels that each got.

#3183 feat: allow MarkTransforms methods to take a single mark (resolve #3…
  docs/concepts/07-editor.md
  docs/walkthroughs/04-applying-custom-formatting.md
  docs/walkthroughs/05-executing-commands.md
  packages/slate/src/create-editor.ts
  packages/slate/src/interfaces/editor/transforms/mark.ts
  packages/slate/test/transforms/addMarks/path/basic.js
  packages/slate/test/transforms/addMarks/range/basic.js
  packages/slate/test/transforms/addMarks/selection/block-across-edge-existing.js
  packages/slate/test/transforms/addMarks/selection/block-across-existing.js
  packages/slate/test/transforms/addMarks/selection/block-across.js
  packages/slate/test/transforms/addMarks/selection/existing.js
  packages/slate/test/transforms/addMarks/selection/first-character.js
  packages/slate/test/transforms/addMarks/selection/inline-across.js
  packages/slate/test/transforms/addMarks/selection/last-character.js
  packages/slate/test/transforms/addMarks/selection/middle-character.js
  packages/slate/test/transforms/addMarks/selection/word.js
  packages/slate/test/transforms/removeMarks/path/basic.js
  packages/slate/test/transforms/removeMarks/range/basic.js
  packages/slate/test/transforms/removeMarks/selection/across-blocks.js
  packages/slate/test/transforms/removeMarks/selection/across-inlines.js
  packages/slate/test/transforms/removeMarks/selection/collapsed-selection.js
  packages/slate/test/transforms/removeMarks/selection/existing-marks.js
  packages/slate/test/transforms/removeMarks/selection/first-character.js
  packages/slate/test/transforms/removeMarks/selection/last-character.js
  packages/slate/test/transforms/removeMarks/selection/middle-character.js
  packages/slate/test/transforms/removeMarks/selection/part-of-mark-backward.js
  packages/slate/test/transforms/removeMarks/selection/part-of-mark.js
  packages/slate/test/transforms/removeMarks/selection/whole-word.js
  packages/slate/test/transforms/setMarks/path/basic.js
  packages/slate/test/transforms/setMarks/range/basic.js
  packages/slate/test/transforms/setMarks/selection/basic.js
Labels: improvement

#3187 fix: typo
  site/examples/embeds.js
Labels: examples

#3190 fix: type
  packages/slate-schema/src/rules.ts
Labels: bug

#3192 Fix missing callback dependencies in slate-react <Editable />
  packages/slate-react/src/components/editable.tsx
Labels: bug

#3194 fix: typo
  site/examples/markdown-shortcuts.js
Labels: examples

#3193 fix: typo
  site/examples/links.js
Labels: examples

#3195 fix: promptMention not defined
  site/examples/mentions.js
Labels: examples

#3202 onCompositionEnd not need to insert text in firfox
  packages/slate-react/src/components/editable.tsx
Labels: bug, ⚑ cross platform

#3210 Fix InsertImageButton in image example
  site/examples/images.js
Labels: examples

#3214 upgrade mentions example to use a portal with suggestions
  site/examples/mentions.js
Labels: examples

#3217 fix: ts
  packages/slate-react/src/hooks/use-slate.tsx
Labels: bug

#3218 fix: support upper case search
  site/examples/mentions.js
Labels: examples

#3219 Fix child_min_invalid checks
  packages/slate-schema/src/checkers.ts
  packages/slate-schema/test/validations/children/min/invalid-second-with-match.js
  site/examples/forced-layout.js
Labels: bug

#3220 Load with correct starting example
  site/pages/examples/[example].js
Labels: examples

#3230 fix universal matching mode for marks
  packages/slate/src/interfaces/editor/queries/location.ts
  packages/slate/test/queries/marks/mode-universal/block-across-intersection.js
  packages/slate/test/queries/marks/mode-universal/block-intersection.js
  packages/slate/test/queries/marks/mode-universal/block-multiple-match.js
  packages/slate/test/queries/marks/mode-universal/block-multiple.js
  site/examples/hovering-toolbar.js
  site/examples/rich-text.js
Labels: bug

#3226 Auto focus after mounting
  packages/slate-react/src/components/editable.tsx
Labels: bug

#3232 Fix check list example
  site/examples/check-lists.js
Labels: examples

#3216 Change `<Slate>` to a controlled component
  docs/concepts/06-editor.md
  package.json
  packages/slate-react/package.json
  packages/slate-react/src/components/slate.tsx
  packages/slate-react/src/hooks/use-slate.tsx
  packages/slate-react/src/index.ts
  packages/slate-react/src/plugin/react-command.ts
  packages/slate-react/src/plugin/react-editor.ts
  packages/slate-react/src/plugin/with-react.ts
  packages/slate-react/src/utils/weak-maps.ts
  packages/slate/src/create-editor.ts
  packages/slate/src/interfaces/editor/index.ts
  site/examples/check-lists.js
  site/examples/embeds.js
  site/examples/forced-layout.js
  site/examples/hovering-toolbar.js
  site/examples/huge-document.js
  site/examples/images.js
  site/examples/links.js
  site/examples/markdown-preview.js
  site/examples/markdown-shortcuts.js
  site/examples/mentions.js
  site/examples/paste-html.js
  site/examples/plain-text.js
  site/examples/read-only.js
  site/examples/rich-text.js
  site/examples/search-highlighting.js
  site/examples/tables.js
  yarn.lock
Labels: ✶ breaking

#3252 change schema plugin to be returned from function
  packages/slate-schema/src/define-schema.ts
  packages/slate-schema/src/index.ts
  packages/slate-schema/src/with-schema.ts
  packages/slate-schema/test/index.js
  site/examples/forced-layout.js
Labels: improvement, ✶ breaking

#3256 Change B to I in code example
  docs/concepts/08-rendering.md
Labels: docs

#3257 Custom Format docs typo fix: leaf -> props
  docs/walkthroughs/04-applying-custom-formatting.md
Labels: docs

#3258 Improved merging of blocks when deleting text
  packages/slate/src/interfaces/editor/transforms/text.ts
  packages/slate/test/transforms/delete/selection/block-inline-over.js
Labels: bug

#3261 Force a zero offset when inside a void node
  packages/slate-react/src/plugin/react-editor.ts
Labels: bug

#3262 implement isomorphic layout effect
  packages/slate-react/src/components/editable.tsx
  packages/slate-react/src/components/element.tsx
  packages/slate-react/src/components/text.tsx
  packages/slate-react/src/hooks/use-isomorphic-layout-effect.ts
Labels: bug

#3264 Fix paste example: nested formatting
  site/examples/paste-html.js
Labels: bug

#3266 Docs: Fix introduction links to examples
  docs/Introduction.md
Labels: docs

#3265 add `voids: true` option to transforms and queries
  packages/slate/src/create-editor.ts
  packages/slate/src/interfaces/editor/queries/location.ts
  packages/slate/src/interfaces/editor/queries/range.ts
  packages/slate/src/interfaces/editor/transforms/node.ts
  packages/slate/src/interfaces/editor/transforms/text.ts
  packages/slate/test/queries/nodes/voids-true/block.js
  packages/slate/test/queries/nodes/voids-true/inline.js
  packages/slate/test/transforms/delete/voids-false/block-across-backward.js
  packages/slate/test/transforms/delete/voids-false/block-after-reverse.js
  packages/slate/test/transforms/delete/voids-false/block-before.js
  packages/slate/test/transforms/delete/voids-false/block-both.js
  packages/slate/test/transforms/delete/voids-false/block-end.js
  packages/slate/test/transforms/delete/voids-false/block-hanging-from.js
  packages/slate/test/transforms/delete/voids-false/block-hanging-into.js
  packages/slate/test/transforms/delete/voids-false/block-only.js
  packages/slate/test/transforms/delete/voids-false/block-start-multiple.js
  packages/slate/test/transforms/delete/voids-false/block-start.js
  packages/slate/test/transforms/delete/voids-false/inline-after-reverse.js
  packages/slate/test/transforms/delete/voids-false/inline-before.js
  packages/slate/test/transforms/delete/voids-false/inline-into.js
  packages/slate/test/transforms/delete/voids-false/inline-over.js
  packages/slate/test/transforms/delete/voids-false/inline-start-across.js
  packages/slate/test/transforms/delete/voids-false/inline-start.js
  packages/slate/test/transforms/delete/voids-true/across-blocks.js
  packages/slate/test/transforms/delete/voids-true/path.js
  packages/slate/test/transforms/insertFragment/voids-false/block.js
  packages/slate/test/transforms/insertFragment/voids-false/inline.js
  packages/slate/test/transforms/insertFragment/voids-true/block.js
  packages/slate/test/transforms/insertFragment/voids-true/inline.js
  packages/slate/test/transforms/insertNodes/voids-true/block.js
  packages/slate/test/transforms/insertNodes/voids-true/inline.js
  packages/slate/test/transforms/insertText/voids-false/block.js
  packages/slate/test/transforms/insertText/voids-false/text.js
  packages/slate/test/transforms/insertText/voids-true/block.js
  packages/slate/test/transforms/insertText/voids-true/text.js
  packages/slate/test/transforms/liftNodes/voids-true/block.js
  packages/slate/test/transforms/mergeNodes/voids-true/block.js
  packages/slate/test/transforms/moveNodes/voids-true/block.js
  packages/slate/test/transforms/moveNodes/voids-true/inline.js
  packages/slate/test/transforms/removeNodes/voids-true/block.js
  packages/slate/test/transforms/removeNodes/voids-true/inline.js
  packages/slate/test/transforms/setNodes/voids-true/block.js
  packages/slate/test/transforms/setNodes/voids-true/inline.js
  packages/slate/test/transforms/splitNodes/voids-true/block.js
  packages/slate/test/transforms/splitNodes/voids-true/inline.js
  packages/slate/test/transforms/unwrapNodes/voids-true/block.js
  packages/slate/test/transforms/wrapNodes/path/block.js
  packages/slate/test/transforms/wrapNodes/voids-true/block.js
Labels: improvement

#3260 Insert outside inline when selection is at the end
  packages/slate/src/create-editor.ts
  packages/slate/src/interfaces/editor/transforms/text.ts
  packages/slate/test/transforms/insertText/selection/inline-end.js
Labels: improvement

#3269 style: no-unused-vars
  site/examples/markdown-preview.js
Labels: examples

#3270 fix: ts
  site/examples/mentions.js
Labels: examples

#3271 fix: ts
  site/examples/mentions.js
Labels: examples

#3279 Small docs changes
  docs/concepts/07-plugins.md
Labels: docs

#3281 fix: typo
  site/examples/paste-html.js
Labels: examples

#3280 Fix trailing new line in blocks
  packages/slate-react/src/components/children.tsx
Labels: bug

#3288 Make Editable accept 'as' prop
  packages/slate-react/src/components/editable.tsx
Labels: improvement

#3290 add previous/next sibling query support
  packages/slate/src/interfaces/editor/queries/location.ts
  packages/slate/test/queries/next/default.js
  packages/slate/test/queries/previous/default.js
Labels: improvement

#3289 remove unnecessary helpers
  packages/slate/src/interfaces/editor/queries/location.ts
  packages/slate/src/interfaces/editor/transforms/node.ts
  packages/slate/src/interfaces/node.ts
  packages/slate/src/interfaces/range.ts
  packages/slate/test/interfaces/Node/closest/success.js
  packages/slate/test/interfaces/Node/furthest/success.js
  packages/slate/test/queries/ancestor/path.js
  packages/slate/test/queries/ancestor/point.js
  packages/slate/test/queries/ancestor/range-text.js
  packages/slate/test/queries/ancestor/range.js
Labels: debt, ✶ breaking

#3259 remove the path from node matching functions
  packages/slate/src/interfaces/editor/queries/location.ts
  packages/slate/src/interfaces/editor/queries/node.ts
  packages/slate/src/interfaces/editor/transforms/node.ts
  packages/slate/src/interfaces/editor/transforms/text.ts
  packages/slate/src/interfaces/node.ts
  packages/slate/test/queries/nodes/match-function/one.js
  packages/slate/test/transforms/liftNodes/selection/block-nested.js
  packages/slate/test/transforms/moveNodes/selection/block-nested-after.js
  packages/slate/test/transforms/moveNodes/selection/block-nested-before.js
  packages/slate/test/transforms/moveNodes/selection/block.js
  packages/slate/test/transforms/splitNodes/depth/two.js
  packages/slate/test/transforms/splitNodes/depth/zero.js
  packages/slate/test/transforms/splitNodes/point/block.js
  packages/slate/test/transforms/splitNodes/point/inline.js
Labels: improvement, ✶ breaking

#3294 Fix forced layout example
  site/examples/forced-layout.js
Labels: examples

#3297 Allow links to be pasted without a selection
  site/examples/links.js
Labels: examples

#3301 fix: ts
  site/examples/links.js
Labels: examples

#3308 Add `format_text` command, and `editor.marks` state
  docs/concepts/06-editor.md
  docs/walkthroughs/01-installing-slate.md
  docs/walkthroughs/02-adding-event-handlers.md
  docs/walkthroughs/03-defining-custom-elements.md
  docs/walkthroughs/04-applying-custom-formatting.md
  docs/walkthroughs/05-executing-commands.md
  docs/walkthroughs/06-saving-to-a-database.md
  packages/slate-history/src/history-command.ts
  packages/slate-history/src/with-history.ts
  packages/slate-react/src/components/slate.tsx
  packages/slate-react/src/plugin/react-command.ts
  packages/slate-react/src/plugin/with-react.ts
  packages/slate-react/src/utils/weak-maps.ts
  packages/slate/src/create-editor.ts
  packages/slate/src/interfaces/command.ts
  packages/slate/src/interfaces/editor/index.ts
  packages/slate/src/interfaces/editor/queries/general.ts
  packages/slate/src/interfaces/operation.ts
  packages/slate/test/interfaces/Element/isElement/editor.js
  packages/slate/test/interfaces/Element/isElementList/full-editor.js
  packages/slate/test/interfaces/Operation/isOperation/set_value.js
  site/examples/check-lists.js
  site/examples/embeds.js
  site/examples/forced-layout.js
  site/examples/hovering-toolbar.js
  site/examples/huge-document.js
  site/examples/images.js
  site/examples/links.js
  site/examples/markdown-preview.js
  site/examples/markdown-shortcuts.js
  site/examples/mentions.js
  site/examples/paste-html.js
  site/examples/plaintext.js
  site/examples/read-only.js
  site/examples/richtext.js
  site/examples/search-highlighting.js
  site/examples/tables.js
Labels: debt, feature, ✶ breaking

#3310 Fix emoji offsets
  packages/slate/src/interfaces/editor/queries/location.ts
Labels: bug

#3341 rename `Node.text` to `Node.string`
  docs/concepts/01-interfaces.md
  docs/concepts/09-serializing.md
  docs/walkthroughs/06-saving-to-a-database.md
  packages/slate-react/src/components/editable.tsx
  packages/slate-react/src/components/element.tsx
  packages/slate-react/src/components/string.tsx
  packages/slate/src/interfaces/editor/queries/location.ts
  packages/slate/src/interfaces/node.ts
  packages/slate/test/interfaces/Node/string/across-elements.js
  packages/slate/test/interfaces/Node/string/element.js
  packages/slate/test/interfaces/Node/string/text.js
  packages/slate/test/queries/string/block-across.js
  packages/slate/test/queries/string/block-void.js
  packages/slate/test/queries/string/block.js
  packages/slate/test/queries/string/inline.js
  packages/slate/test/queries/string/text.js
  site/examples/hovering-toolbar.js
  site/examples/markdown-shortcuts.js
  site/examples/mentions.js
Labels: improvement, ✶ breaking

#3340 split `format_text` into two commands
  packages/slate/src/create-editor.ts
  packages/slate/src/interfaces/command.ts
  site/examples/richtext.js
Labels: improvement, ✶ breaking

#3347 fix onBeforeInput memoization
  packages/slate-react/src/components/editable.tsx
Labels: bug

#3346 deletebackward -> deleteforward
  packages/slate/src/interfaces/command.ts
Labels: docs

#3349 Swap remove_mark/add_mark example
  Changelog.md
Labels: docs

#3337 build: relax transpilation for es modules
  config/babel/babel.config.cjs
  config/rollup/rollup.config.js
Labels: debt, improvement, ✶ breaking

#3356 Added a warning for Android in faq
  docs/general/faq.md
Labels: docs

#3357 Fix broken link in introduction of docs
  docs/Introduction.md
Labels: docs

#3363 fix: undoing and redoing are switched #3362
  packages/slate-react/src/components/editable.tsx
Labels: bug

#3358 moved getLeaves from react to slate core package and added some basic tests
  packages/slate-react/src/components/text.tsx
  packages/slate/src/interfaces/text.ts
  packages/slate/test/interfaces/Text/decorations/end.js
  packages/slate/test/interfaces/Text/decorations/middle.js
  packages/slate/test/interfaces/Text/decorations/overlapping.js
  packages/slate/test/interfaces/Text/decorations/start.js
Labels: improvement

#3359 fix: Slate editor props
  packages/slate-history/src/with-history.ts
  packages/slate-react/src/plugin/with-react.ts
Labels: bug
