Repository ianstormtaylor/slate, pull requests merged in 2019-05, with the labels that each got.

#2728 Wrap insertTextAtRange in withoutNormalizing
  packages/slate/src/commands/at-range.js
Labels: bug

#2731 Update "Check Lists" nav item to "Checklists"
  examples/app.js
Labels: examples

#2735 Fix typo
  examples/rich-text/value.json
Labels: examples

#2738 fix selection after pasting inline nodes
  packages/slate/src/commands/with-intent.js
  packages/slate/test/commands/at-current-range/insert-fragment/fragment-inline-node.js
Labels: bug

#2758 Text documentation update
  docs/reference/slate/text.md
Labels: docs

#2799 Use relative path to find a node's text nodes
  packages/slate-react/src/plugins/react/queries.js
  packages/slate-react/src/utils/get-selection-from-dom.js
Labels: bug

#2800 Allow deleteAtRange with a zero-length range on the first character
  packages/slate/src/commands/at-range.js
  packages/slate/test/commands/at-current-range/delete/first-position.js
Labels: bug

#2772 fixing order of blocks if inserted at start of node
  packages/slate/src/commands/at-range.js
  packages/slate/test/commands/at-current-range/insert-fragment/fragment-nested-blocks-end-of-node.js
  packages/slate/test/commands/at-current-range/insert-fragment/fragment-nested-blocks-start-of-node.js
Labels: bug

#2774 Gracefully handle null content ref in slate-react findDOMNode query
  packages/slate-react/src/plugins/react/queries.js
Labels: bug

#2780 Fix: prop name
  docs/walkthroughs/saving-and-loading-html-content.md
Labels: docs

#2766 Fix leaf memoization bug
  packages/slate-react/src/components/leaf.js
Labels: bug

#2794 fallback findPath query to find closest element with a data-key
  examples/images/index.js
  packages/slate-react/src/plugins/dom/before.js
  packages/slate-react/src/plugins/react/queries.js
Labels: bug

#2819 Fix placeholder not rendering
  packages/slate-react-placeholder/src/index.js
  packages/slate/src/models/text.js
Labels: bug

#2820 Add div to editor as editor.el
  packages/slate-react/src/components/content.js
Labels: improvement
