Repository ianstormtaylor/slate, pull requests merged in 2019-03, with the labels that each got.

#2587 Fix insert-node-by-key benchmark, add normalize and insert-fragment benchmarks
  benchmark/helpers/h.js
  benchmark/slate/changes/insert-fragment-deep-with-problems.js
  benchmark/slate/changes/insert-fragment-large.js
  benchmark/slate/changes/insert-fragment.js
  benchmark/slate/changes/insert-node-by-key.js
  benchmark/slate/changes/normalize-with-problems.js
  packages/slate-plain-serializer/test/helpers/h.js
Labels: debt

#2624 fix insert fragment with void children
  packages/slate/src/commands/at-range.js
  packages/slate/test/commands/at-current-range/insert-fragment/start-block-with-void-no-text.js
Labels: bug

#2628 Remove return true on key down function
  docs/walkthroughs/adding-event-handlers.md
Labels: docs

#2629 Fix missing break in last example
  docs/walkthroughs/applying-custom-formatting.md
Labels: docs

#2618 Add API version and Input Events Level 2 for Android
  packages/slate-dev-environment/src/index.js
Labels: improvement

#2622 Fix Edge positioning with newlines
  packages/slate-react/src/utils/find-point.js
Labels: bug, ⚑ cross platform, ⚑ waiting

#2593 Fix move_node dirtyPath and PathUtils.transform calculations
  packages/slate/src/controllers/editor.js
  packages/slate/src/interfaces/element.js
  packages/slate/src/operations/invert.js
  packages/slate/src/utils/path-utils.js
  packages/slate/test/commands/at-current-range/delete-backward/with-plugin-normalization.js
  packages/slate/test/commands/at-current-range/delete/all-with-nested-blocks.js
  packages/slate/test/history/undo/insert-fragment.js
  packages/slate/test/index.js
  packages/slate/test/utils/path-utils/transform/move-node/from-before-not-younger.js
  packages/slate/test/utils/path-utils/transform/move-node/from-younger.js
  packages/slate/test/utils/path-utils/transform/move-node/siblings-backward.js
  packages/slate/test/utils/path-utils/transform/move-node/siblings-forward.js
Labels: bug

#2565 Android 8 and 9 Support
  examples/app.js
  examples/composition/index.js
  examples/composition/insert.js
  examples/composition/special.js
  examples/composition/split-join.js
  examples/composition/util.js
  examples/composition/value.json
  package.json
  packages/slate-react/src/components/content.js
  packages/slate-react/src/plugins/ANDROID.md
  packages/slate-react/src/plugins/android.js
  packages/slate-react/src/plugins/debug.js
  packages/slate-react/src/plugins/dom.js
  packages/slate-react/src/utils/android-api-version.js
  packages/slate-react/src/utils/dom-snapshot.js
  packages/slate-react/src/utils/element-snapshot.js
  packages/slate-react/src/utils/executor.js
  packages/slate-react/src/utils/fix-selection-in-zero-width-block.js
  packages/slate-react/src/utils/get-selection-from-dom.js
  packages/slate-react/src/utils/is-input-data-enter.js
  packages/slate-react/src/utils/is-input-data-last-char.js
  packages/slate-react/src/utils/set-selection-from-dom.js
  packages/slate-react/src/utils/set-text-from-dom-node.js
Labels: improvement, ⚑ cross platform

#2655 docs: fix immutablejs doc domain
  Readme.md
  docs/Introduction.md
  docs/general/resources.md
  docs/guides/data-model.md
  docs/reference/slate/data.md
Labels: docs

#2557 Convert remaining `Node.get*` methods to use paths
  benchmark/slate/changes/normalize.js
  packages/slate/src/interfaces/element.js
  packages/slate/src/models/point.js
  packages/slate/src/utils/path-utils.js
  packages/slate/test/models/node/get-active-marks-at-range.js/different-marks-across-blocks.js
  packages/slate/test/models/node/get-active-marks-at-range.js/mixed-marks-across-range.js
  packages/slate/test/models/node/get-active-marks-at-range.js/same-mark-across-blocks.js
  packages/slate/test/models/node/get-closest/by-key.js
  packages/slate/test/models/node/get-closest/get-block-parent-inline.js
  packages/slate/test/models/node/get-closest/top-level.js
  packages/slate/test/models/node/get-fragment-at-range/across-block-with-marks.js
  packages/slate/test/models/node/get-furthest-only-child/multiple-nodes-in-nested-block.js
  packages/slate/test/models/node/get-furthest-only-child/multiple-nodes.js
  packages/slate/test/models/node/get-next-block/by-key.js
  packages/slate/test/models/node/get-next-block/multiple-siblings-to-bypass.js
  packages/slate/test/models/node/get-next-block/next-block-is-ancestor-sibling.js
  packages/slate/test/models/node/get-next-block/next-block-is-in-sibling-with-deeper-blocks.js
  packages/slate/test/models/node/get-next-block/next-block-is-sibling-descendent.js
  packages/slate/test/models/node/get-next-block/next-block-is-sibling.js
  packages/slate/test/models/node/get-next-block/no-next-block.js
  packages/slate/test/models/node/get-next-block/no-next-node.js
  packages/slate/test/models/node/get-next-node/next-node-is-ancestor-sibling-with-nested-blocks.js
  packages/slate/test/models/node/get-next-node/next-node-is-ancestor-sibling.js
  packages/slate/test/models/node/get-previous-block/by-key.js
  packages/slate/test/models/node/get-previous-block/multiple-siblings-to-bypass.js
  packages/slate/test/models/node/get-previous-block/no-prev-block.js
  packages/slate/test/models/node/get-previous-block/no-prev-node.js
  packages/slate/test/models/node/get-previous-block/prev-block-is-ancestor-sibling.js
  packages/slate/test/models/node/get-previous-block/prev-block-is-in-sibling-with-deeper-blocks.js
  packages/slate/test/models/node/get-previous-block/prev-block-is-sibling-descendent.js
  packages/slate/test/models/node/get-previous-block/prev-block-is-sibling.js
  packages/slate/test/models/node/get-selection-indexes/across-blocks-from-nested-node.js
  packages/slate/test/models/node/get-selection-indexes/across-blocks.js
  packages/slate/test/models/node/get-selection-indexes/in-single-block-from-middle-nested-node.js
  packages/slate/test/models/node/get-selection-indexes/in-single-block-from-parent-node.js
  packages/slate/test/models/node/get-selection-indexes/in-single-block.js
Labels: debt, improvement
