Repository ianstormtaylor/slate, pull requests merged in 2019-04, with the labels that each got.

#2667 Allow custom placeholder styles
  examples/app.js
  examples/placeholder/index.js
  examples/placeholder/value.json
  package.json
  packages/slate-react-placeholder/src/index.js
Labels: improvement

#2675 Make use of clientX and clientY in getEventRange
  packages/slate-react/src/utils/get-event-range.js
Labels: bug, ⚑ cross platform

#2676 Use <s> for strikethrough example
  docs/guides/rendering.md
Labels: examples

#2225 Make all ops invertible and remove `value` from ops
  docs/reference/slate/commands.md
  docs/reference/slate/operation.md
  examples/history/index.js
  packages/slate/src/commands/by-path.js
  packages/slate/src/commands/on-selection.js
  packages/slate/src/commands/on-value.js
  packages/slate/src/interfaces/element.js
  packages/slate/src/models/operation.js
  packages/slate/src/models/text.js
  packages/slate/src/operations/apply.js
  packages/slate/src/operations/invert.js
  packages/slate/test/models/text/marks/update-mark/marked-text-with-some-other-marks.js
  packages/slate/test/operations/apply/remove-node/decoration-across-blocks.js
Labels: improvement, ⚑ next, ✶ breaking

#2695 Allow immutable 4.0.0-rc
  packages/slate-html-serializer/package.json
  packages/slate-react/package.json
  packages/slate/package.json
Labels: bug

#2682 insertBlock is missing description
  docs/reference/slate/commands.md
Labels: docs

#2537 Add path to Range Points
  packages/slate-react-placeholder/src/index.js
Labels: bug

#2688 fix get marks from previous text on method getMarksAtPosition
  packages/slate/src/interfaces/element.js
  packages/slate/test/models/node/get-marks-at-position/marked-text-with-zero-offset-with-no-previous-text.js
  packages/slate/test/models/node/get-marks-at-position/marked-text-with-zero-offset-with-previous-text-not-in-the-same-block.js
  packages/slate/test/models/node/get-marks-at-position/marked-text.js
  packages/slate/test/models/node/get-marks-at-position/text-with-zero-offset.js
  packages/slate/test/models/node/get-marks-at-position/unmarked-text.js
Labels: bug

#2689 removed ie/edge condition that causes "node of undefined" TypeError i…
  packages/slate-react/src/utils/find-range.js
Labels: bug, ⚑ cross platform

#2697 Support decorations without path
  packages/slate-react/src/components/text.js
Labels: bug

#2710 Improve performance on large documents with many nodes
  packages/slate-react/src/components/content.js
Labels: improvement, ⚑ performance
