Repository ianstormtaylor/slate, pull requests merged in 2021-05, with the labels that each got.

#4238 Fix duplicated content and other bugs related to drag and drop handling
  .changeset/drag-and-drop.md
  packages/slate-react/src/components/editable.tsx
Labels: bug

#4230 Added insert_node path checking to match how other operations are applied
  .changeset/bright-pants-grin.md
  .changeset/sixty-glasses-beg.md
  packages/slate/src/interfaces/editor.ts
  packages/slate/src/transforms/general.ts
  packages/slate/test/transforms/general/invalid-insert_node.tsx
Labels: bug

#4208 Apply no-children normalization fix before normalization
  .changeset/silver-snakes-perform.md
  packages/slate/src/interfaces/editor.ts
  packages/slate/test/transforms/normalization/move_node.tsx
  packages/slate/test/transforms/normalization/split_node-and-insert_node.tsx
Labels: bug

#4237 Update IS_FIREFOX_LEGACY flag to prevent FF crash
  .changeset/forty-mails-roll.md
  packages/slate-react/src/components/editable.tsx
Labels: bug, ⚑ cross platform

#4227 Fix addMark/removeMark caused unexpected onChange.
  .changeset/three-parrots-remember.md
  packages/slate/src/create-editor.ts
Labels: bug

#4247 Update transforms.md
  docs/api/transforms.md
Labels: docs

#4188 Ensure round-trip tests don't mutate output before checking against it => reveals 4 tests are broken
  packages/slate-history/test/undo/delete_backward/block-text.tsx
  packages/slate-history/test/undo/delete_backward/custom-prop.tsx
  packages/slate-history/test/undo/delete_backward/inline-across.tsx
  packages/slate-history/test/undo/insert_break/basic.tsx
  packages/slate-history/test/undo/insert_fragment/basic.tsx
  packages/slate-history/test/undo/insert_text/basic.tsx
  packages/slate-history/test/undo/insert_text/contiguous.tsx
  packages/slate/test/interfaces/Node/ancestor/success.tsx
  packages/slate/test/interfaces/Node/child/success.tsx
  packages/slate/test/interfaces/Node/descendant/success.tsx
  packages/slate/test/interfaces/Node/get/root.tsx
  packages/slate/test/transforms/delete/unit-line/text-end.tsx
  packages/slate/test/transforms/delete/unit-line/text-start-reverse.tsx
Labels: debt

#4274 Update release workflow to ensure that the `latest` job runs before the `dev` job
  .github/workflows/release.yml
Labels: bug
