Repository ianstormtaylor/slate, pull requests merged in 2021-03, with the labels that each got.

#4105 docs : Update duplicated toSlatePoint to toSlateRange
  docs/libraries/slate-react.md
Labels: docs

#4028 Fix version links in README
  Readme.md
Labels: docs

#4006 Update URLs to examples in Readme.md
  Readme.md
Labels: docs

#3971 docs: add TRPG Engine link to products using slate
  docs/general/resources.md
Labels: docs

#3876 docs: add react-force/slate-editor to the list of pre-packaged editors
  docs/general/resources.md
Labels: docs

#4047 Small correction to docs concepts/06-editor.md
  docs/concepts/06-editor.md
Labels: docs

#3437 Fix element memoization checks. Allows placeholder to change dynamically based on the props. Allows renderLeaf to be memoized.
  packages/slate-react/src/components/element.tsx
  packages/slate-react/src/components/leaf.tsx
  packages/slate-react/src/components/text.tsx
  packages/slate-react/src/utils/range-list.ts
  packages/slate/src/interfaces/text.ts
  packages/slate/test/interfaces/Text/matches/undefined-false.js
  packages/slate/test/interfaces/Text/matches/undefined-true.js
Labels: bug

#4073 Fix for Editor.positions not working correctly in all cases
  packages/slate/src/interfaces/editor.ts
  packages/slate/test/interfaces/Editor/positions/all/inline-fragmentation-empty-text.tsx
  packages/slate/test/interfaces/Editor/positions/all/inline-fragmentation-reverse.tsx
  packages/slate/test/interfaces/Editor/positions/all/inline-fragmentation.tsx
  packages/slate/test/interfaces/Editor/positions/all/unit-character-inline-fragmentation-multibyte.tsx
  packages/slate/test/interfaces/Editor/positions/all/unit-character-inline-fragmentation-reverse.tsx
  packages/slate/test/interfaces/Editor/positions/all/unit-character-inline-fragmentation.tsx
  packages/slate/test/interfaces/Editor/positions/all/unit-line-inline-fragmentation-reverse.tsx
  packages/slate/test/interfaces/Editor/positions/all/unit-line-inline-fragmentation.tsx
  packages/slate/test/interfaces/Editor/positions/all/unit-word-inline-fragmentation.tsx
Labels: bug

#4072 Memoize Node.isNodeList and Editor.isEditor
  packages/slate/src/interfaces/editor.ts
  packages/slate/src/interfaces/node.ts
Labels: improvement, ⚑ perf

#3364 feat: delete current line when deleting backward with line unit
  packages/slate-react/src/plugin/with-react.ts
  packages/slate-react/src/utils/lines.ts
Labels: improvement

#3768 fix: IME repeat input
  packages/slate-react/src/components/editable.tsx
Labels: bug, ⚑ ime

#3727 Fix cursor movement in RTL elements (#2963)
  packages/slate-react/src/components/editable.tsx
Labels: bug

#3326 add guard checks for value and editor in <Slate />
  .changeset/fuzzy-yaks-drive.md
  packages/slate-react/package.json
  packages/slate-react/src/components/slate.tsx
Labels: improvement

#3532 `Text.equals` now works with more nested Text nodes, and non-primitive attributes.
  packages/slate/package.json
  packages/slate/src/interfaces/text.ts
  packages/slate/test/interfaces/Text/equals/complex-exact-equals.js
  packages/slate/test/interfaces/Text/equals/complex-exact-not-equal.js
  packages/slate/test/interfaces/Text/equals/complex-loose-equals.js
  packages/slate/test/interfaces/Text/equals/complex-loose-not-equal.js
  packages/slate/test/interfaces/Text/equals/exact-equals.js
  packages/slate/test/interfaces/Text/equals/exact-not-equal.js
  packages/slate/test/interfaces/Text/equals/loose-equals.js
  packages/slate/test/interfaces/Text/equals/loose-not-equal.js
Labels: improvement

#3549 Correct onDOMBeforeInput typings
  packages/slate-react/src/components/editable.tsx
Labels: bug

#3906 Converting JSX test cases to TSX
  packages/slate-hyperscript/test/fixtures/cursor-across-element.tsx
  packages/slate-hyperscript/test/fixtures/cursor-across-elements-empty.tsx
  packages/slate-hyperscript/test/fixtures/cursor-across-elements-end.tsx
  packages/slate-hyperscript/test/fixtures/cursor-across-elements-middle.tsx
  packages/slate-hyperscript/test/fixtures/cursor-across-elements-start.tsx
  packages/slate-hyperscript/test/fixtures/cursor-element-empty.tsx
  packages/slate-hyperscript/test/fixtures/cursor-element-end.tsx
  packages/slate-hyperscript/test/fixtures/cursor-element-middle.tsx
  packages/slate-hyperscript/test/fixtures/cursor-element-nested-end.tsx
  packages/slate-hyperscript/test/fixtures/cursor-element-nested-middle.tsx
  packages/slate-hyperscript/test/fixtures/cursor-element-nested-start.tsx
  packages/slate-hyperscript/test/fixtures/cursor-element-start.tsx
  packages/slate-hyperscript/test/fixtures/cursor-text-empty.tsx
  packages/slate-hyperscript/test/fixtures/element-custom.tsx
  packages/slate-hyperscript/test/fixtures/element-empty.tsx
  packages/slate-hyperscript/test/fixtures/element-nested-empty.tsx
  packages/slate-hyperscript/test/fixtures/element-nested-string.tsx
  packages/slate-hyperscript/test/fixtures/element-string.tsx
  packages/slate-hyperscript/test/fixtures/element-text-empty.tsx
  packages/slate-hyperscript/test/fixtures/element-text-string.tsx
  packages/slate-hyperscript/test/fixtures/fragment-element.tsx
  packages/slate-hyperscript/test/fixtures/fragment-empty.tsx
  packages/slate-hyperscript/test/fixtures/fragment-string.tsx
  packages/slate-hyperscript/test/fixtures/selection-offset-start.tsx
  packages/slate-hyperscript/test/fixtures/selection.tsx
  packages/slate-hyperscript/test/fixtures/text-empty.tsx
  packages/slate-hyperscript/test/fixtures/text-full.tsx
  packages/slate-hyperscript/test/fixtures/text-nested.tsx
  packages/slate-hyperscript/test/fixtures/value-empty.tsx
  packages/slate-hyperscript/tsconfig.json
Labels: debt

#3890 fix typo
  packages/slate/src/transforms/general.ts
Labels: bug

#4019 Add support for longer placeholder values
  packages/slate-react/src/components/editable.tsx
  packages/slate-react/src/components/leaf.tsx
Labels: improvement

#4107 fix: cut do not remove void element when only select void element
  packages/slate-react/src/components/editable.tsx
Labels: bug

#4062 Add voids to the interface definition of positions
  packages/slate/src/interfaces/editor.ts
Labels: bug

#3825 fix: mergeNodes by point would delete nested multi-child node
  packages/slate/src/transforms/node.ts
  packages/slate/test/transforms/mergeNodes/depth-block/block-nested-multi-child.tsx
  packages/slate/test/transforms/mergeNodes/depth-block/block-nested-only-child.tsx
Labels: bug

#3851 Normalize moved node
  packages/slate/src/create-editor.ts
Labels: improvement

#3980 Updated serializing demo function
  docs/concepts/09-serializing.md
Labels: docs

#4057 Fix toSlatePoint wrong offset for void element.
  packages/slate-react/src/plugin/react-editor.ts
Labels: bug

#3933 Added isImageUrl validation to button, added alert when not image
  site/examples/images.tsx
Labels: examples

#3946 Disable spellCheck/autoCorrect/autoCapitalize in browsers without onBeforeInput
  packages/slate-react/src/components/editable.tsx
Labels: bug, ⚑ cross platform

#4120 Fix move_node caused full re-render.
  packages/slate-react/src/plugin/with-react.ts
Labels: bug

#4125 Fix deletion of hanging ranges with trailing void block
  packages/slate/src/transforms/text.ts
  packages/slate/test/transforms/delete/selection/block-void-end-hanging.tsx
  packages/slate/test/transforms/delete/selection/block-void-end.tsx
Labels: bug

#4109 added support for deleting selection properties by setting them to null
  packages/slate/src/transforms/general.ts
  packages/slate/test/operations/set_selection/custom-props.tsx
  packages/slate/test/operations/set_selection/remove.tsx
Labels: feature
