Repository ianstormtaylor/slate, pull requests merged in 2021-08, with the labels that each got.

#4049 Fix ios chrome ime double input issue.
  .changeset/metal-trees-rest.md
  packages/slate-react/src/components/editable.tsx
Labels: bug

#4091 Proposal for Remove useCallback from walkthroughs documentation
  docs/walkthroughs/04-applying-custom-formatting.md
Labels: ⚑ waiting

#4132 Make onDomSelectionChange triggered after onClick.
  .changeset/cold-beans-give.md
  packages/slate-react/src/components/editable.tsx
Labels: ⚑ needs fixing
