Repository ianstormtaylor/slate, pull requests merged in 2021-04, with the labels that each got.

#4099 Fixed converting querySelectorAll results to array for Babel loose mode.
  packages/slate-react/src/plugin/react-editor.ts
Labels: bug

#3988 rerender slate when focus changes.
  packages/slate-react/src/components/slate.tsx
Labels: bug

#4138 Decorate re-render optimize to not re-render all elements.
  packages/slate-react/src/components/editable.tsx
  packages/slate-react/src/components/element.tsx
  packages/slate-react/src/hooks/use-children.tsx
  packages/slate-react/src/hooks/use-decorate.ts
Labels: improvement

#4048 Fix normalizeDOMPoint to do better job.
  packages/slate-react/src/utils/dom.ts
Labels: bug

#4159 Update 09-serializing.md
  docs/concepts/09-serializing.md
Labels: docs

#4179 add transforms concept docs
  docs/Summary.md
  docs/concepts/04-transforms.md
  docs/concepts/05-operations.md
  docs/concepts/06-commands.md
  docs/concepts/07-editor.md
  docs/concepts/08-plugins.md
  docs/concepts/09-rendering.md
  docs/concepts/10-serializing.md
  docs/concepts/11-normalizing.md
  docs/concepts/12-typescript.md
Labels: docs

#4180 Update images.tsx
  site/examples/images.tsx
Labels: examples

#4194 Fix range API link
  docs/concepts/03-locations.md
Labels: docs

#4192 Remove execute file permission from .ts files
  packages/slate/src/create-editor.ts
  packages/slate/src/index.ts
  packages/slate/src/interfaces/editor.ts
  packages/slate/src/interfaces/element.ts
  packages/slate/src/interfaces/location.ts
  packages/slate/src/interfaces/node.ts
  packages/slate/src/interfaces/operation.ts
  packages/slate/src/interfaces/path.ts
  packages/slate/src/interfaces/point.ts
  packages/slate/src/interfaces/range.ts
  packages/slate/src/interfaces/text.ts
  packages/slate/src/transforms/general.ts
  packages/slate/src/transforms/selection.ts
Labels: debt

#4185 Stop basic installation from throwing typescript errors
  docs/walkthroughs/01-installing-slate.md
Labels: docs

#4197 Updates outdated TypeScript link in first walkthrough document
  docs/walkthroughs/01-installing-slate.md
Labels: docs

#4078 set_node operations did not invert correctly after serialization
  .changeset/silent-bees-sing.md
  packages/slate/src/transforms/general.ts
  packages/slate/src/transforms/node.ts
  packages/slate/test/operations/set_node/remove-null.tsx
  packages/slate/test/operations/set_node/remove-omit.tsx
  packages/slate/test/operations/set_node/remove-undefined.tsx
  packages/slate/test/transforms/setNodes/basic-structure/can-be-serialized.tsx
  packages/slate/test/transforms/setNodes/basic-structure/invert-after-serialization.tsx
Labels: bug

#4193 Save some remove_text calls if the text is zero length
  .changeset/giant-adults-matter.md
  packages/slate/src/transforms/general.ts
  packages/slate/src/transforms/text.ts
Labels: improvement

#4168 Correcting the splitting logic in setNodes
  .changeset/two-lies-appear.md
  packages/slate/src/create-editor.ts
  packages/slate/src/transforms/node.ts
  packages/slate/test/transforms/setNodes/text/merge-across.tsx
Labels: bug

#4118 Make HAS_BEFORE_INPUT_SUPPORT flag more generic.
  .changeset/dirty-rabbits-speak.md
  packages/slate-react/src/components/editable.tsx
Labels: bug, ⚑ cross platform

#4199 refactor: New Editor.positions based off PR#3644
  packages/slate/src/interfaces/editor.ts
Labels: debt
